// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	model "github.com/adityakw90/service-access/internal/core/domain/model"
	mock "github.com/stretchr/testify/mock"

	param "github.com/adityakw90/service-access/internal/core/domain/param"
)

// MockSubjectRepository is an autogenerated mock type for the SubjectRepository type
type MockSubjectRepository struct {
	mock.Mock
}

type MockSubjectRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockSubjectRepository) EXPECT() *MockSubjectRepository_Expecter {
	return &MockSubjectRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, subject
func (_m *MockSubjectRepository) Create(ctx context.Context, subject *model.SubjectRole) error {
	ret := _m.Called(ctx, subject)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *model.SubjectRole) error); ok {
		r0 = rf(ctx, subject)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockSubjectRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockSubjectRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - subject *model.SubjectRole
func (_e *MockSubjectRepository_Expecter) Create(ctx interface{}, subject interface{}) *MockSubjectRepository_Create_Call {
	return &MockSubjectRepository_Create_Call{Call: _e.mock.On("Create", ctx, subject)}
}

func (_c *MockSubjectRepository_Create_Call) Run(run func(ctx context.Context, subject *model.SubjectRole)) *MockSubjectRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*model.SubjectRole))
	})
	return _c
}

func (_c *MockSubjectRepository_Create_Call) Return(_a0 error) *MockSubjectRepository_Create_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockSubjectRepository_Create_Call) RunAndReturn(run func(context.Context, *model.SubjectRole) error) *MockSubjectRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function with given fields: ctx, subjectID, subjectType, roleID
func (_m *MockSubjectRepository) Delete(ctx context.Context, subjectID string, subjectType string, roleID int64) error {
	ret := _m.Called(ctx, subjectID, subjectType, roleID)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, int64) error); ok {
		r0 = rf(ctx, subjectID, subjectType, roleID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockSubjectRepository_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockSubjectRepository_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - subjectID string
//   - subjectType string
//   - roleID int64
func (_e *MockSubjectRepository_Expecter) Delete(ctx interface{}, subjectID interface{}, subjectType interface{}, roleID interface{}) *MockSubjectRepository_Delete_Call {
	return &MockSubjectRepository_Delete_Call{Call: _e.mock.On("Delete", ctx, subjectID, subjectType, roleID)}
}

func (_c *MockSubjectRepository_Delete_Call) Run(run func(ctx context.Context, subjectID string, subjectType string, roleID int64)) *MockSubjectRepository_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(int64))
	})
	return _c
}

func (_c *MockSubjectRepository_Delete_Call) Return(_a0 error) *MockSubjectRepository_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockSubjectRepository_Delete_Call) RunAndReturn(run func(context.Context, string, string, int64) error) *MockSubjectRepository_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// GetRoles provides a mock function with given fields: ctx, subjectID, subjectType
func (_m *MockSubjectRepository) GetRoles(ctx context.Context, subjectID string, subjectType string) ([]model.SubjectRole, error) {
	ret := _m.Called(ctx, subjectID, subjectType)

	if len(ret) == 0 {
		panic("no return value specified for GetRoles")
	}

	var r0 []model.SubjectRole
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) ([]model.SubjectRole, error)); ok {
		return rf(ctx, subjectID, subjectType)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) []model.SubjectRole); ok {
		r0 = rf(ctx, subjectID, subjectType)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.SubjectRole)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, subjectID, subjectType)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockSubjectRepository_GetRoles_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetRoles'
type MockSubjectRepository_GetRoles_Call struct {
	*mock.Call
}

// GetRoles is a helper method to define mock.On call
//   - ctx context.Context
//   - subjectID string
//   - subjectType string
func (_e *MockSubjectRepository_Expecter) GetRoles(ctx interface{}, subjectID interface{}, subjectType interface{}) *MockSubjectRepository_GetRoles_Call {
	return &MockSubjectRepository_GetRoles_Call{Call: _e.mock.On("GetRoles", ctx, subjectID, subjectType)}
}

func (_c *MockSubjectRepository_GetRoles_Call) Run(run func(ctx context.Context, subjectID string, subjectType string)) *MockSubjectRepository_GetRoles_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockSubjectRepository_GetRoles_Call) Return(_a0 []model.SubjectRole, _a1 error) *MockSubjectRepository_GetRoles_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockSubjectRepository_GetRoles_Call) RunAndReturn(run func(context.Context, string, string) ([]model.SubjectRole, error)) *MockSubjectRepository_GetRoles_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function with given fields: ctx, pagination, filter
func (_m *MockSubjectRepository) List(ctx context.Context, pagination *param.PaginationParam, filter *param.SubjectListFilterParam) (model.SubjectRoles, error) {
	ret := _m.Called(ctx, pagination, filter)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 model.SubjectRoles
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *param.PaginationParam, *param.SubjectListFilterParam) (model.SubjectRoles, error)); ok {
		return rf(ctx, pagination, filter)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *param.PaginationParam, *param.SubjectListFilterParam) model.SubjectRoles); ok {
		r0 = rf(ctx, pagination, filter)
	} else {
		r0 = ret.Get(0).(model.SubjectRoles)
	}

	if rf, ok := ret.Get(1).(func(context.Context, *param.PaginationParam, *param.SubjectListFilterParam) error); ok {
		r1 = rf(ctx, pagination, filter)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockSubjectRepository_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type MockSubjectRepository_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
//   - pagination *param.PaginationParam
//   - filter *param.SubjectListFilterParam
func (_e *MockSubjectRepository_Expecter) List(ctx interface{}, pagination interface{}, filter interface{}) *MockSubjectRepository_List_Call {
	return &MockSubjectRepository_List_Call{Call: _e.mock.On("List", ctx, pagination, filter)}
}

func (_c *MockSubjectRepository_List_Call) Run(run func(ctx context.Context, pagination *param.PaginationParam, filter *param.SubjectListFilterParam)) *MockSubjectRepository_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*param.PaginationParam), args[2].(*param.SubjectListFilterParam))
	})
	return _c
}

func (_c *MockSubjectRepository_List_Call) Return(_a0 model.SubjectRoles, _a1 error) *MockSubjectRepository_List_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockSubjectRepository_List_Call) RunAndReturn(run func(context.Context, *param.PaginationParam, *param.SubjectListFilterParam) (model.SubjectRoles, error)) *MockSubjectRepository_List_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: ctx, subject
func (_m *MockSubjectRepository) Update(ctx context.Context, subject *model.SubjectRole) error {
	ret := _m.Called(ctx, subject)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *model.SubjectRole) error); ok {
		r0 = rf(ctx, subject)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockSubjectRepository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockSubjectRepository_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - subject *model.SubjectRole
func (_e *MockSubjectRepository_Expecter) Update(ctx interface{}, subject interface{}) *MockSubjectRepository_Update_Call {
	return &MockSubjectRepository_Update_Call{Call: _e.mock.On("Update", ctx, subject)}
}

func (_c *MockSubjectRepository_Update_Call) Run(run func(ctx context.Context, subject *model.SubjectRole)) *MockSubjectRepository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*model.SubjectRole))
	})
	return _c
}

func (_c *MockSubjectRepository_Update_Call) Return(_a0 error) *MockSubjectRepository_Update_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockSubjectRepository_Update_Call) RunAndReturn(run func(context.Context, *model.SubjectRole) error) *MockSubjectRepository_Update_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockSubjectRepository creates a new instance of MockSubjectRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockSubjectRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSubjectRepository {
	mock := &MockSubjectRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
