// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	model "github.com/adityakw90/service-access/internal/core/domain/model"
	mock "github.com/stretchr/testify/mock"

	param "github.com/adityakw90/service-access/internal/core/domain/param"
)

// MockRoleRepository is an autogenerated mock type for the RoleRepository type
type MockRoleRepository struct {
	mock.Mock
}

type MockRoleRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRoleRepository) EXPECT() *MockRoleRepository_Expecter {
	return &MockRoleRepository_Expecter{mock: &_m.Mock}
}

// AddPermission provides a mock function with given fields: ctx, roleID, groupPermissionID
func (_m *MockRoleRepository) AddPermission(ctx context.Context, roleID int64, groupPermissionID int64) error {
	ret := _m.Called(ctx, roleID, groupPermissionID)

	if len(ret) == 0 {
		panic("no return value specified for AddPermission")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int64, int64) error); ok {
		r0 = rf(ctx, roleID, groupPermissionID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockRoleRepository_AddPermission_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddPermission'
type MockRoleRepository_AddPermission_Call struct {
	*mock.Call
}

// AddPermission is a helper method to define mock.On call
//   - ctx context.Context
//   - roleID int64
//   - groupPermissionID int64
func (_e *MockRoleRepository_Expecter) AddPermission(ctx interface{}, roleID interface{}, groupPermissionID interface{}) *MockRoleRepository_AddPermission_Call {
	return &MockRoleRepository_AddPermission_Call{Call: _e.mock.On("AddPermission", ctx, roleID, groupPermissionID)}
}

func (_c *MockRoleRepository_AddPermission_Call) Run(run func(ctx context.Context, roleID int64, groupPermissionID int64)) *MockRoleRepository_AddPermission_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64), args[2].(int64))
	})
	return _c
}

func (_c *MockRoleRepository_AddPermission_Call) Return(_a0 error) *MockRoleRepository_AddPermission_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockRoleRepository_AddPermission_Call) RunAndReturn(run func(context.Context, int64, int64) error) *MockRoleRepository_AddPermission_Call {
	_c.Call.Return(run)
	return _c
}

// Create provides a mock function with given fields: ctx, role
func (_m *MockRoleRepository) Create(ctx context.Context, role *model.Role) error {
	ret := _m.Called(ctx, role)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *model.Role) error); ok {
		r0 = rf(ctx, role)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockRoleRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockRoleRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - role *model.Role
func (_e *MockRoleRepository_Expecter) Create(ctx interface{}, role interface{}) *MockRoleRepository_Create_Call {
	return &MockRoleRepository_Create_Call{Call: _e.mock.On("Create", ctx, role)}
}

func (_c *MockRoleRepository_Create_Call) Run(run func(ctx context.Context, role *model.Role)) *MockRoleRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*model.Role))
	})
	return _c
}

func (_c *MockRoleRepository_Create_Call) Return(_a0 error) *MockRoleRepository_Create_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockRoleRepository_Create_Call) RunAndReturn(run func(context.Context, *model.Role) error) *MockRoleRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function with given fields: ctx, id
func (_m *MockRoleRepository) Delete(ctx context.Context, id int64) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockRoleRepository_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockRoleRepository_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - id int64
func (_e *MockRoleRepository_Expecter) Delete(ctx interface{}, id interface{}) *MockRoleRepository_Delete_Call {
	return &MockRoleRepository_Delete_Call{Call: _e.mock.On("Delete", ctx, id)}
}

func (_c *MockRoleRepository_Delete_Call) Run(run func(ctx context.Context, id int64)) *MockRoleRepository_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64))
	})
	return _c
}

func (_c *MockRoleRepository_Delete_Call) Return(_a0 error) *MockRoleRepository_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockRoleRepository_Delete_Call) RunAndReturn(run func(context.Context, int64) error) *MockRoleRepository_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// GetByID provides a mock function with given fields: ctx, id
func (_m *MockRoleRepository) GetByID(ctx context.Context, id int64) (*model.Role, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *model.Role
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) (*model.Role, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64) *model.Role); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Role)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRoleRepository_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type MockRoleRepository_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id int64
func (_e *MockRoleRepository_Expecter) GetByID(ctx interface{}, id interface{}) *MockRoleRepository_GetByID_Call {
	return &MockRoleRepository_GetByID_Call{Call: _e.mock.On("GetByID", ctx, id)}
}

func (_c *MockRoleRepository_GetByID_Call) Run(run func(ctx context.Context, id int64)) *MockRoleRepository_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64))
	})
	return _c
}

func (_c *MockRoleRepository_GetByID_Call) Return(_a0 *model.Role, _a1 error) *MockRoleRepository_GetByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRoleRepository_GetByID_Call) RunAndReturn(run func(context.Context, int64) (*model.Role, error)) *MockRoleRepository_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// GetByUID provides a mock function with given fields: ctx, uid
func (_m *MockRoleRepository) GetByUID(ctx context.Context, uid string) (*model.Role, error) {
	ret := _m.Called(ctx, uid)

	if len(ret) == 0 {
		panic("no return value specified for GetByUID")
	}

	var r0 *model.Role
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*model.Role, error)); ok {
		return rf(ctx, uid)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *model.Role); ok {
		r0 = rf(ctx, uid)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Role)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, uid)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRoleRepository_GetByUID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByUID'
type MockRoleRepository_GetByUID_Call struct {
	*mock.Call
}

// GetByUID is a helper method to define mock.On call
//   - ctx context.Context
//   - uid string
func (_e *MockRoleRepository_Expecter) GetByUID(ctx interface{}, uid interface{}) *MockRoleRepository_GetByUID_Call {
	return &MockRoleRepository_GetByUID_Call{Call: _e.mock.On("GetByUID", ctx, uid)}
}

func (_c *MockRoleRepository_GetByUID_Call) Run(run func(ctx context.Context, uid string)) *MockRoleRepository_GetByUID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockRoleRepository_GetByUID_Call) Return(_a0 *model.Role, _a1 error) *MockRoleRepository_GetByUID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRoleRepository_GetByUID_Call) RunAndReturn(run func(context.Context, string) (*model.Role, error)) *MockRoleRepository_GetByUID_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function with given fields: ctx, pagination, filter
func (_m *MockRoleRepository) List(ctx context.Context, pagination *param.PaginationParam, filter *param.RoleListFilterParam) (model.Roles, error) {
	ret := _m.Called(ctx, pagination, filter)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 model.Roles
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *param.PaginationParam, *param.RoleListFilterParam) (model.Roles, error)); ok {
		return rf(ctx, pagination, filter)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *param.PaginationParam, *param.RoleListFilterParam) model.Roles); ok {
		r0 = rf(ctx, pagination, filter)
	} else {
		r0 = ret.Get(0).(model.Roles)
	}

	if rf, ok := ret.Get(1).(func(context.Context, *param.PaginationParam, *param.RoleListFilterParam) error); ok {
		r1 = rf(ctx, pagination, filter)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRoleRepository_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type MockRoleRepository_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
//   - pagination *param.PaginationParam
//   - filter *param.RoleListFilterParam
func (_e *MockRoleRepository_Expecter) List(ctx interface{}, pagination interface{}, filter interface{}) *MockRoleRepository_List_Call {
	return &MockRoleRepository_List_Call{Call: _e.mock.On("List", ctx, pagination, filter)}
}

func (_c *MockRoleRepository_List_Call) Run(run func(ctx context.Context, pagination *param.PaginationParam, filter *param.RoleListFilterParam)) *MockRoleRepository_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*param.PaginationParam), args[2].(*param.RoleListFilterParam))
	})
	return _c
}

func (_c *MockRoleRepository_List_Call) Return(_a0 model.Roles, _a1 error) *MockRoleRepository_List_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRoleRepository_List_Call) RunAndReturn(run func(context.Context, *param.PaginationParam, *param.RoleListFilterParam) (model.Roles, error)) *MockRoleRepository_List_Call {
	_c.Call.Return(run)
	return _c
}

// ListPermission provides a mock function with given fields: ctx, roleID, pagination, filter
func (_m *MockRoleRepository) ListPermission(ctx context.Context, roleID int64, pagination *param.PaginationParam, filter *param.RolePermissionListFilterParam) (model.RolePermissions, error) {
	ret := _m.Called(ctx, roleID, pagination, filter)

	if len(ret) == 0 {
		panic("no return value specified for ListPermission")
	}

	var r0 model.RolePermissions
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64, *param.PaginationParam, *param.RolePermissionListFilterParam) (model.RolePermissions, error)); ok {
		return rf(ctx, roleID, pagination, filter)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64, *param.PaginationParam, *param.RolePermissionListFilterParam) model.RolePermissions); ok {
		r0 = rf(ctx, roleID, pagination, filter)
	} else {
		r0 = ret.Get(0).(model.RolePermissions)
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64, *param.PaginationParam, *param.RolePermissionListFilterParam) error); ok {
		r1 = rf(ctx, roleID, pagination, filter)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRoleRepository_ListPermission_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListPermission'
type MockRoleRepository_ListPermission_Call struct {
	*mock.Call
}

// ListPermission is a helper method to define mock.On call
//   - ctx context.Context
//   - roleID int64
//   - pagination *param.PaginationParam
//   - filter *param.RolePermissionListFilterParam
func (_e *MockRoleRepository_Expecter) ListPermission(ctx interface{}, roleID interface{}, pagination interface{}, filter interface{}) *MockRoleRepository_ListPermission_Call {
	return &MockRoleRepository_ListPermission_Call{Call: _e.mock.On("ListPermission", ctx, roleID, pagination, filter)}
}

func (_c *MockRoleRepository_ListPermission_Call) Run(run func(ctx context.Context, roleID int64, pagination *param.PaginationParam, filter *param.RolePermissionListFilterParam)) *MockRoleRepository_ListPermission_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64), args[2].(*param.PaginationParam), args[3].(*param.RolePermissionListFilterParam))
	})
	return _c
}

func (_c *MockRoleRepository_ListPermission_Call) Return(_a0 model.RolePermissions, _a1 error) *MockRoleRepository_ListPermission_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRoleRepository_ListPermission_Call) RunAndReturn(run func(context.Context, int64, *param.PaginationParam, *param.RolePermissionListFilterParam) (model.RolePermissions, error)) *MockRoleRepository_ListPermission_Call {
	_c.Call.Return(run)
	return _c
}

// RemovePermission provides a mock function with given fields: ctx, roleID, groupPermissionID
func (_m *MockRoleRepository) RemovePermission(ctx context.Context, roleID int64, groupPermissionID int64) error {
	ret := _m.Called(ctx, roleID, groupPermissionID)

	if len(ret) == 0 {
		panic("no return value specified for RemovePermission")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int64, int64) error); ok {
		r0 = rf(ctx, roleID, groupPermissionID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockRoleRepository_RemovePermission_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RemovePermission'
type MockRoleRepository_RemovePermission_Call struct {
	*mock.Call
}

// RemovePermission is a helper method to define mock.On call
//   - ctx context.Context
//   - roleID int64
//   - groupPermissionID int64
func (_e *MockRoleRepository_Expecter) RemovePermission(ctx interface{}, roleID interface{}, groupPermissionID interface{}) *MockRoleRepository_RemovePermission_Call {
	return &MockRoleRepository_RemovePermission_Call{Call: _e.mock.On("RemovePermission", ctx, roleID, groupPermissionID)}
}

func (_c *MockRoleRepository_RemovePermission_Call) Run(run func(ctx context.Context, roleID int64, groupPermissionID int64)) *MockRoleRepository_RemovePermission_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64), args[2].(int64))
	})
	return _c
}

func (_c *MockRoleRepository_RemovePermission_Call) Return(_a0 error) *MockRoleRepository_RemovePermission_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockRoleRepository_RemovePermission_Call) RunAndReturn(run func(context.Context, int64, int64) error) *MockRoleRepository_RemovePermission_Call {
	_c.Call.Return(run)
	return _c
}

// ReplacePermission provides a mock function with given fields: ctx, roleID, groupPermissionIDs
func (_m *MockRoleRepository) ReplacePermission(ctx context.Context, roleID int64, groupPermissionIDs []int64) error {
	ret := _m.Called(ctx, roleID, groupPermissionIDs)

	if len(ret) == 0 {
		panic("no return value specified for ReplacePermission")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int64, []int64) error); ok {
		r0 = rf(ctx, roleID, groupPermissionIDs)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockRoleRepository_ReplacePermission_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ReplacePermission'
type MockRoleRepository_ReplacePermission_Call struct {
	*mock.Call
}

// ReplacePermission is a helper method to define mock.On call
//   - ctx context.Context
//   - roleID int64
//   - groupPermissionIDs []int64
func (_e *MockRoleRepository_Expecter) ReplacePermission(ctx interface{}, roleID interface{}, groupPermissionIDs interface{}) *MockRoleRepository_ReplacePermission_Call {
	return &MockRoleRepository_ReplacePermission_Call{Call: _e.mock.On("ReplacePermission", ctx, roleID, groupPermissionIDs)}
}

func (_c *MockRoleRepository_ReplacePermission_Call) Run(run func(ctx context.Context, roleID int64, groupPermissionIDs []int64)) *MockRoleRepository_ReplacePermission_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64), args[2].([]int64))
	})
	return _c
}

func (_c *MockRoleRepository_ReplacePermission_Call) Return(_a0 error) *MockRoleRepository_ReplacePermission_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockRoleRepository_ReplacePermission_Call) RunAndReturn(run func(context.Context, int64, []int64) error) *MockRoleRepository_ReplacePermission_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: ctx, role
func (_m *MockRoleRepository) Update(ctx context.Context, role *model.Role) error {
	ret := _m.Called(ctx, role)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *model.Role) error); ok {
		r0 = rf(ctx, role)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockRoleRepository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockRoleRepository_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - role *model.Role
func (_e *MockRoleRepository_Expecter) Update(ctx interface{}, role interface{}) *MockRoleRepository_Update_Call {
	return &MockRoleRepository_Update_Call{Call: _e.mock.On("Update", ctx, role)}
}

func (_c *MockRoleRepository_Update_Call) Run(run func(ctx context.Context, role *model.Role)) *MockRoleRepository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*model.Role))
	})
	return _c
}

func (_c *MockRoleRepository_Update_Call) Return(_a0 error) *MockRoleRepository_Update_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockRoleRepository_Update_Call) RunAndReturn(run func(context.Context, *model.Role) error) *MockRoleRepository_Update_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockRoleRepository creates a new instance of MockRoleRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRoleRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRoleRepository {
	mock := &MockRoleRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
