// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	model "github.com/adityakw90/service-access/internal/core/domain/model"
	mock "github.com/stretchr/testify/mock"

	param "github.com/adityakw90/service-access/internal/core/domain/param"
)

// MockPermissionRepository is an autogenerated mock type for the PermissionRepository type
type MockPermissionRepository struct {
	mock.Mock
}

type MockPermissionRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockPermissionRepository) EXPECT() *MockPermissionRepository_Expecter {
	return &MockPermissionRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, permission
func (_m *MockPermissionRepository) Create(ctx context.Context, permission *model.Permission) error {
	ret := _m.Called(ctx, permission)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *model.Permission) error); ok {
		r0 = rf(ctx, permission)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockPermissionRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockPermissionRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - permission *model.Permission
func (_e *MockPermissionRepository_Expecter) Create(ctx interface{}, permission interface{}) *MockPermissionRepository_Create_Call {
	return &MockPermissionRepository_Create_Call{Call: _e.mock.On("Create", ctx, permission)}
}

func (_c *MockPermissionRepository_Create_Call) Run(run func(ctx context.Context, permission *model.Permission)) *MockPermissionRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*model.Permission))
	})
	return _c
}

func (_c *MockPermissionRepository_Create_Call) Return(_a0 error) *MockPermissionRepository_Create_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockPermissionRepository_Create_Call) RunAndReturn(run func(context.Context, *model.Permission) error) *MockPermissionRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function with given fields: ctx, id
func (_m *MockPermissionRepository) Delete(ctx context.Context, id int64) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockPermissionRepository_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockPermissionRepository_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - id int64
func (_e *MockPermissionRepository_Expecter) Delete(ctx interface{}, id interface{}) *MockPermissionRepository_Delete_Call {
	return &MockPermissionRepository_Delete_Call{Call: _e.mock.On("Delete", ctx, id)}
}

func (_c *MockPermissionRepository_Delete_Call) Run(run func(ctx context.Context, id int64)) *MockPermissionRepository_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64))
	})
	return _c
}

func (_c *MockPermissionRepository_Delete_Call) Return(_a0 error) *MockPermissionRepository_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockPermissionRepository_Delete_Call) RunAndReturn(run func(context.Context, int64) error) *MockPermissionRepository_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// GetByID provides a mock function with given fields: ctx, id
func (_m *MockPermissionRepository) GetByID(ctx context.Context, id int64) (*model.Permission, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *model.Permission
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) (*model.Permission, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64) *model.Permission); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Permission)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockPermissionRepository_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type MockPermissionRepository_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id int64
func (_e *MockPermissionRepository_Expecter) GetByID(ctx interface{}, id interface{}) *MockPermissionRepository_GetByID_Call {
	return &MockPermissionRepository_GetByID_Call{Call: _e.mock.On("GetByID", ctx, id)}
}

func (_c *MockPermissionRepository_GetByID_Call) Run(run func(ctx context.Context, id int64)) *MockPermissionRepository_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64))
	})
	return _c
}

func (_c *MockPermissionRepository_GetByID_Call) Return(_a0 *model.Permission, _a1 error) *MockPermissionRepository_GetByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockPermissionRepository_GetByID_Call) RunAndReturn(run func(context.Context, int64) (*model.Permission, error)) *MockPermissionRepository_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// GetByUID provides a mock function with given fields: ctx, uid
func (_m *MockPermissionRepository) GetByUID(ctx context.Context, uid string) (*model.Permission, error) {
	ret := _m.Called(ctx, uid)

	if len(ret) == 0 {
		panic("no return value specified for GetByUID")
	}

	var r0 *model.Permission
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*model.Permission, error)); ok {
		return rf(ctx, uid)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *model.Permission); ok {
		r0 = rf(ctx, uid)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Permission)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, uid)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockPermissionRepository_GetByUID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByUID'
type MockPermissionRepository_GetByUID_Call struct {
	*mock.Call
}

// GetByUID is a helper method to define mock.On call
//   - ctx context.Context
//   - uid string
func (_e *MockPermissionRepository_Expecter) GetByUID(ctx interface{}, uid interface{}) *MockPermissionRepository_GetByUID_Call {
	return &MockPermissionRepository_GetByUID_Call{Call: _e.mock.On("GetByUID", ctx, uid)}
}

func (_c *MockPermissionRepository_GetByUID_Call) Run(run func(ctx context.Context, uid string)) *MockPermissionRepository_GetByUID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockPermissionRepository_GetByUID_Call) Return(_a0 *model.Permission, _a1 error) *MockPermissionRepository_GetByUID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockPermissionRepository_GetByUID_Call) RunAndReturn(run func(context.Context, string) (*model.Permission, error)) *MockPermissionRepository_GetByUID_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function with given fields: ctx, pagination, filter
func (_m *MockPermissionRepository) List(ctx context.Context, pagination *param.PaginationParam, filter *param.PermissionListFilterParam) (model.Permissions, error) {
	ret := _m.Called(ctx, pagination, filter)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 model.Permissions
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *param.PaginationParam, *param.PermissionListFilterParam) (model.Permissions, error)); ok {
		return rf(ctx, pagination, filter)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *param.PaginationParam, *param.PermissionListFilterParam) model.Permissions); ok {
		r0 = rf(ctx, pagination, filter)
	} else {
		r0 = ret.Get(0).(model.Permissions)
	}

	if rf, ok := ret.Get(1).(func(context.Context, *param.PaginationParam, *param.PermissionListFilterParam) error); ok {
		r1 = rf(ctx, pagination, filter)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockPermissionRepository_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type MockPermissionRepository_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
//   - pagination *param.PaginationParam
//   - filter *param.PermissionListFilterParam
func (_e *MockPermissionRepository_Expecter) List(ctx interface{}, pagination interface{}, filter interface{}) *MockPermissionRepository_List_Call {
	return &MockPermissionRepository_List_Call{Call: _e.mock.On("List", ctx, pagination, filter)}
}

func (_c *MockPermissionRepository_List_Call) Run(run func(ctx context.Context, pagination *param.PaginationParam, filter *param.PermissionListFilterParam)) *MockPermissionRepository_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*param.PaginationParam), args[2].(*param.PermissionListFilterParam))
	})
	return _c
}

func (_c *MockPermissionRepository_List_Call) Return(_a0 model.Permissions, _a1 error) *MockPermissionRepository_List_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockPermissionRepository_List_Call) RunAndReturn(run func(context.Context, *param.PaginationParam, *param.PermissionListFilterParam) (model.Permissions, error)) *MockPermissionRepository_List_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: ctx, permission
func (_m *MockPermissionRepository) Update(ctx context.Context, permission *model.Permission) error {
	ret := _m.Called(ctx, permission)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *model.Permission) error); ok {
		r0 = rf(ctx, permission)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockPermissionRepository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockPermissionRepository_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - permission *model.Permission
func (_e *MockPermissionRepository_Expecter) Update(ctx interface{}, permission interface{}) *MockPermissionRepository_Update_Call {
	return &MockPermissionRepository_Update_Call{Call: _e.mock.On("Update", ctx, permission)}
}

func (_c *MockPermissionRepository_Update_Call) Run(run func(ctx context.Context, permission *model.Permission)) *MockPermissionRepository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*model.Permission))
	})
	return _c
}

func (_c *MockPermissionRepository_Update_Call) Return(_a0 error) *MockPermissionRepository_Update_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockPermissionRepository_Update_Call) RunAndReturn(run func(context.Context, *model.Permission) error) *MockPermissionRepository_Update_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockPermissionRepository creates a new instance of MockPermissionRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockPermissionRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockPermissionRepository {
	mock := &MockPermissionRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
