// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	param "github.com/adityakw90/service-access/internal/core/domain/param"
	mock "github.com/stretchr/testify/mock"
)

// MockGroupPermissionResolver is an autogenerated mock type for the GroupPermissionResolver type
type MockGroupPermissionResolver struct {
	mock.Mock
}

type MockGroupPermissionResolver_Expecter struct {
	mock *mock.Mock
}

func (_m *MockGroupPermissionResolver) EXPECT() *MockGroupPermissionResolver_Expecter {
	return &MockGroupPermissionResolver_Expecter{mock: &_m.Mock}
}

// GroupIDsAndPermissionIDsByIDs provides a mock function with given fields: ctx, ids
func (_m *MockGroupPermissionResolver) GroupIDsAndPermissionIDsByIDs(ctx context.Context, ids []int64) (map[int64]param.GroupPermissionMapGroupIDPermissionID, error) {
	ret := _m.Called(ctx, ids)

	if len(ret) == 0 {
		panic("no return value specified for GroupIDsAndPermissionIDsByIDs")
	}

	var r0 map[int64]param.GroupPermissionMapGroupIDPermissionID
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, []int64) (map[int64]param.GroupPermissionMapGroupIDPermissionID, error)); ok {
		return rf(ctx, ids)
	}
	if rf, ok := ret.Get(0).(func(context.Context, []int64) map[int64]param.GroupPermissionMapGroupIDPermissionID); ok {
		r0 = rf(ctx, ids)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[int64]param.GroupPermissionMapGroupIDPermissionID)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, []int64) error); ok {
		r1 = rf(ctx, ids)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockGroupPermissionResolver_GroupIDsAndPermissionIDsByIDs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GroupIDsAndPermissionIDsByIDs'
type MockGroupPermissionResolver_GroupIDsAndPermissionIDsByIDs_Call struct {
	*mock.Call
}

// GroupIDsAndPermissionIDsByIDs is a helper method to define mock.On call
//   - ctx context.Context
//   - ids []int64
func (_e *MockGroupPermissionResolver_Expecter) GroupIDsAndPermissionIDsByIDs(ctx interface{}, ids interface{}) *MockGroupPermissionResolver_GroupIDsAndPermissionIDsByIDs_Call {
	return &MockGroupPermissionResolver_GroupIDsAndPermissionIDsByIDs_Call{Call: _e.mock.On("GroupIDsAndPermissionIDsByIDs", ctx, ids)}
}

func (_c *MockGroupPermissionResolver_GroupIDsAndPermissionIDsByIDs_Call) Run(run func(ctx context.Context, ids []int64)) *MockGroupPermissionResolver_GroupIDsAndPermissionIDsByIDs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].([]int64))
	})
	return _c
}

func (_c *MockGroupPermissionResolver_GroupIDsAndPermissionIDsByIDs_Call) Return(_a0 map[int64]param.GroupPermissionMapGroupIDPermissionID, _a1 error) *MockGroupPermissionResolver_GroupIDsAndPermissionIDsByIDs_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockGroupPermissionResolver_GroupIDsAndPermissionIDsByIDs_Call) RunAndReturn(run func(context.Context, []int64) (map[int64]param.GroupPermissionMapGroupIDPermissionID, error)) *MockGroupPermissionResolver_GroupIDsAndPermissionIDsByIDs_Call {
	_c.Call.Return(run)
	return _c
}

// IDsByGroupIDAndPermissionIDs provides a mock function with given fields: ctx, _a1
func (_m *MockGroupPermissionResolver) IDsByGroupIDAndPermissionIDs(ctx context.Context, _a1 []param.GroupPermissionMapGroupIDPermissionID) (map[param.GroupPermissionMapGroupIDPermissionID]int64, error) {
	ret := _m.Called(ctx, _a1)

	if len(ret) == 0 {
		panic("no return value specified for IDsByGroupIDAndPermissionIDs")
	}

	var r0 map[param.GroupPermissionMapGroupIDPermissionID]int64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, []param.GroupPermissionMapGroupIDPermissionID) (map[param.GroupPermissionMapGroupIDPermissionID]int64, error)); ok {
		return rf(ctx, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, []param.GroupPermissionMapGroupIDPermissionID) map[param.GroupPermissionMapGroupIDPermissionID]int64); ok {
		r0 = rf(ctx, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[param.GroupPermissionMapGroupIDPermissionID]int64)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, []param.GroupPermissionMapGroupIDPermissionID) error); ok {
		r1 = rf(ctx, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockGroupPermissionResolver_IDsByGroupIDAndPermissionIDs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IDsByGroupIDAndPermissionIDs'
type MockGroupPermissionResolver_IDsByGroupIDAndPermissionIDs_Call struct {
	*mock.Call
}

// IDsByGroupIDAndPermissionIDs is a helper method to define mock.On call
//   - ctx context.Context
//   - _a1 []param.GroupPermissionMapGroupIDPermissionID
func (_e *MockGroupPermissionResolver_Expecter) IDsByGroupIDAndPermissionIDs(ctx interface{}, _a1 interface{}) *MockGroupPermissionResolver_IDsByGroupIDAndPermissionIDs_Call {
	return &MockGroupPermissionResolver_IDsByGroupIDAndPermissionIDs_Call{Call: _e.mock.On("IDsByGroupIDAndPermissionIDs", ctx, _a1)}
}

func (_c *MockGroupPermissionResolver_IDsByGroupIDAndPermissionIDs_Call) Run(run func(ctx context.Context, _a1 []param.GroupPermissionMapGroupIDPermissionID)) *MockGroupPermissionResolver_IDsByGroupIDAndPermissionIDs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].([]param.GroupPermissionMapGroupIDPermissionID))
	})
	return _c
}

func (_c *MockGroupPermissionResolver_IDsByGroupIDAndPermissionIDs_Call) Return(_a0 map[param.GroupPermissionMapGroupIDPermissionID]int64, _a1 error) *MockGroupPermissionResolver_IDsByGroupIDAndPermissionIDs_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockGroupPermissionResolver_IDsByGroupIDAndPermissionIDs_Call) RunAndReturn(run func(context.Context, []param.GroupPermissionMapGroupIDPermissionID) (map[param.GroupPermissionMapGroupIDPermissionID]int64, error)) *MockGroupPermissionResolver_IDsByGroupIDAndPermissionIDs_Call {
	_c.Call.Return(run)
	return _c
}

// IDsByUIDs provides a mock function with given fields: ctx, uids
func (_m *MockGroupPermissionResolver) IDsByUIDs(ctx context.Context, uids []string) (map[string]int64, error) {
	ret := _m.Called(ctx, uids)

	if len(ret) == 0 {
		panic("no return value specified for IDsByUIDs")
	}

	var r0 map[string]int64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, []string) (map[string]int64, error)); ok {
		return rf(ctx, uids)
	}
	if rf, ok := ret.Get(0).(func(context.Context, []string) map[string]int64); ok {
		r0 = rf(ctx, uids)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]int64)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, []string) error); ok {
		r1 = rf(ctx, uids)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockGroupPermissionResolver_IDsByUIDs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IDsByUIDs'
type MockGroupPermissionResolver_IDsByUIDs_Call struct {
	*mock.Call
}

// IDsByUIDs is a helper method to define mock.On call
//   - ctx context.Context
//   - uids []string
func (_e *MockGroupPermissionResolver_Expecter) IDsByUIDs(ctx interface{}, uids interface{}) *MockGroupPermissionResolver_IDsByUIDs_Call {
	return &MockGroupPermissionResolver_IDsByUIDs_Call{Call: _e.mock.On("IDsByUIDs", ctx, uids)}
}

func (_c *MockGroupPermissionResolver_IDsByUIDs_Call) Run(run func(ctx context.Context, uids []string)) *MockGroupPermissionResolver_IDsByUIDs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].([]string))
	})
	return _c
}

func (_c *MockGroupPermissionResolver_IDsByUIDs_Call) Return(_a0 map[string]int64, _a1 error) *MockGroupPermissionResolver_IDsByUIDs_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockGroupPermissionResolver_IDsByUIDs_Call) RunAndReturn(run func(context.Context, []string) (map[string]int64, error)) *MockGroupPermissionResolver_IDsByUIDs_Call {
	_c.Call.Return(run)
	return _c
}

// UIDsByIDs provides a mock function with given fields: ctx, ids
func (_m *MockGroupPermissionResolver) UIDsByIDs(ctx context.Context, ids []int64) (map[int64]string, error) {
	ret := _m.Called(ctx, ids)

	if len(ret) == 0 {
		panic("no return value specified for UIDsByIDs")
	}

	var r0 map[int64]string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, []int64) (map[int64]string, error)); ok {
		return rf(ctx, ids)
	}
	if rf, ok := ret.Get(0).(func(context.Context, []int64) map[int64]string); ok {
		r0 = rf(ctx, ids)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[int64]string)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, []int64) error); ok {
		r1 = rf(ctx, ids)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockGroupPermissionResolver_UIDsByIDs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UIDsByIDs'
type MockGroupPermissionResolver_UIDsByIDs_Call struct {
	*mock.Call
}

// UIDsByIDs is a helper method to define mock.On call
//   - ctx context.Context
//   - ids []int64
func (_e *MockGroupPermissionResolver_Expecter) UIDsByIDs(ctx interface{}, ids interface{}) *MockGroupPermissionResolver_UIDsByIDs_Call {
	return &MockGroupPermissionResolver_UIDsByIDs_Call{Call: _e.mock.On("UIDsByIDs", ctx, ids)}
}

func (_c *MockGroupPermissionResolver_UIDsByIDs_Call) Run(run func(ctx context.Context, ids []int64)) *MockGroupPermissionResolver_UIDsByIDs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].([]int64))
	})
	return _c
}

func (_c *MockGroupPermissionResolver_UIDsByIDs_Call) Return(_a0 map[int64]string, _a1 error) *MockGroupPermissionResolver_UIDsByIDs_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockGroupPermissionResolver_UIDsByIDs_Call) RunAndReturn(run func(context.Context, []int64) (map[int64]string, error)) *MockGroupPermissionResolver_UIDsByIDs_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockGroupPermissionResolver creates a new instance of MockGroupPermissionResolver. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockGroupPermissionResolver(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockGroupPermissionResolver {
	mock := &MockGroupPermissionResolver{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
