// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"

	repository "github.com/adityakw90/service-access/internal/core/port/repository"
)

// RepositoryProvider is an autogenerated mock type for the RepositoryProvider type
type RepositoryProvider struct {
	mock.Mock
}

// Group provides a mock function with given fields:
func (_m *RepositoryProvider) Group() repository.GroupRepository {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Group")
	}

	var r0 repository.GroupRepository
	if rf, ok := ret.Get(0).(func() repository.GroupRepository); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(repository.GroupRepository)
		}
	}

	return r0
}

// Permission provides a mock function with given fields:
func (_m *RepositoryProvider) Permission() repository.PermissionRepository {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Permission")
	}

	var r0 repository.PermissionRepository
	if rf, ok := ret.Get(0).(func() repository.PermissionRepository); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(repository.PermissionRepository)
		}
	}

	return r0
}

// Role provides a mock function with given fields:
func (_m *RepositoryProvider) Role() repository.RoleRepository {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Role")
	}

	var r0 repository.RoleRepository
	if rf, ok := ret.Get(0).(func() repository.RoleRepository); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(repository.RoleRepository)
		}
	}

	return r0
}

// Subject provides a mock function with given fields:
func (_m *RepositoryProvider) Subject() repository.SubjectRepository {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Subject")
	}

	var r0 repository.SubjectRepository
	if rf, ok := ret.Get(0).(func() repository.SubjectRepository); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(repository.SubjectRepository)
		}
	}

	return r0
}

// NewRepositoryProvider creates a new instance of RepositoryProvider. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewRepositoryProvider(t interface {
	mock.TestingT
	Cleanup(func())
}) *RepositoryProvider {
	mock := &RepositoryProvider{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
