// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	repository "github.com/adityakw90/service-access/internal/core/port/repository"
	mock "github.com/stretchr/testify/mock"
)

// UnitOfWorkFactory is an autogenerated mock type for the UnitOfWorkFactory type
type UnitOfWorkFactory struct {
	mock.Mock
}

// Create provides a mock function with given fields: ctx
func (_m *UnitOfWorkFactory) Create(ctx context.Context) (repository.UnitOfWork, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 repository.UnitOfWork
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (repository.UnitOfWork, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) repository.UnitOfWork); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(repository.UnitOfWork)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewUnitOfWorkFactory creates a new instance of UnitOfWorkFactory. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewUnitOfWorkFactory(t interface {
	mock.TestingT
	Cleanup(func())
}) *UnitOfWorkFactory {
	mock := &UnitOfWorkFactory{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
