package repository

import (
	"context"

	"github.com/adityakw90/service-access/internal/core/domain/model"
	"github.com/adityakw90/service-access/internal/core/domain/param"
)

// GroupRepository defines the port for group persistence operations.
// All entities must have non-empty UIDs generated by the service layer.
type GroupRepository interface {
	// Manage
	// Create adds a new group to the repository.
	// The group must have a non-empty UID generated by the service layer.
	Create(ctx context.Context, group *model.Group) error
	// Update updates an existing group in the repository.
	Update(ctx context.Context, group *model.Group) error
	// Delete deletes a group by ID.
	Delete(ctx context.Context, id int64) error

	// Retrieve
	// GetByID returns a group by ID.
	GetByID(ctx context.Context, id int64) (*model.Group, error)
	// GetByUID returns a group by UID.
	GetByUID(ctx context.Context, uid string) (*model.Group, error)
	// List returns the list of groups with optional pagination and filtering.
	List(ctx context.Context, pagination *param.PaginationParam, filter *param.GroupListFilterParam) (model.Groups, error)

	// Permission
	// ListPermission returns the list of permissions for a group.
	ListPermission(ctx context.Context, groupID int64, pagination *param.PaginationParam, filter *param.GroupPermissionListFilterParam) (model.GroupPermissions, error)
	// GetPermissionByID returns a group permission by ID.
	GetPermissionByID(ctx context.Context, groupPermissionID int64) (*model.GroupPermission, error)
	// GetPermissionByGroupIDAndPermissionUID returns a group permission by group ID and permission UID.
	GetPermissionByGroupIDAndPermissionUID(ctx context.Context, groupID int64, permissionUID string) (*model.GroupPermission, error)
	// AddPermission adds a permission to a group.
	// The uid must be a non-empty UUID generated by the service layer.
	AddPermission(ctx context.Context, groupID int64, permissionID int64, uid string) error
	// RemovePermission removes a permission from a group.
	RemovePermission(ctx context.Context, groupID int64, permissionID int64) error
	// ReplacePermission replaces all permissions for a group.
	// Each uid in the uids slice must be a non-empty UUID generated by the service layer.
	ReplacePermission(ctx context.Context, groupID int64, permissionIDs []int64, uids []string) error
}
