package repository

import (
	"context"

	"github.com/adityakw90/service-access/internal/core/domain/model"
	"github.com/adityakw90/service-access/internal/core/domain/param"
)

// PermissionRepository defines the port for permission persistence operations.
// All entities must have non-empty UIDs generated by the service layer.
type PermissionRepository interface {
	// Manage
	// Create adds a new permission to the repository.
	// The permission must have a non-empty UID generated by the service layer.
	Create(ctx context.Context, permission *model.Permission) error
	// Update updates an existing permission in the repository.
	Update(ctx context.Context, permission *model.Permission) error
	// Delete deletes a permission by ID.
	Delete(ctx context.Context, id int64) error

	// Retrieve
	// GetByID returns a permission by ID.
	GetByID(ctx context.Context, id int64) (*model.Permission, error)
	// GetByUID returns a permission by UID.
	GetByUID(ctx context.Context, uid string) (*model.Permission, error)
	// List returns the list of permissions with optional pagination and filtering.
	List(ctx context.Context, pagination *param.PaginationParam, filter *param.PermissionListFilterParam) (model.Permissions, error)
}
