package repository

import (
	"context"

	"github.com/adityakw90/service-access/internal/core/domain/model"
	"github.com/adityakw90/service-access/internal/core/domain/param"
)

// RoleRepository defines the port for role persistence operations.
// All entities must have non-empty UIDs generated by the service layer.
type RoleRepository interface {
	// Manage
	// Create adds a new role to the repository.
	// The role must have a non-empty UID generated by the service layer.
	Create(ctx context.Context, role *model.Role) error
	// Update updates an existing role in the repository.
	Update(ctx context.Context, role *model.Role) error
	// Delete deletes a role by ID.
	Delete(ctx context.Context, id int64) error

	// Retrieve
	// GetByID returns a role by ID.
	GetByID(ctx context.Context, id int64) (*model.Role, error)
	// GetByUID returns a role by UID.
	GetByUID(ctx context.Context, uid string) (*model.Role, error)
	// List returns the list of roles with optional pagination and filtering.
	List(ctx context.Context, pagination *param.PaginationParam, filter *param.RoleListFilterParam) (model.Roles, error)

	// Permission
	// ListPermission returns the list of group permissions for a role.
	ListPermission(ctx context.Context, roleID int64, pagination *param.PaginationParam, filter *param.RolePermissionListFilterParam) (model.RolePermissions, error)
	// AddPermission adds a group permission to a role.
	AddPermission(ctx context.Context, roleID int64, groupPermissionID int64) error
	// RemovePermission removes a group permission from a role.
	RemovePermission(ctx context.Context, roleID int64, groupPermissionID int64) error
	// ReplacePermission replaces all group permissions for a role.
	ReplacePermission(ctx context.Context, roleID int64, groupPermissionIDs []int64) error
	// GetAllPermissions returns all permissions for a role (through role_permission → group_permission → permission).
	// Results are deduplicated and sorted by permission UID.
	GetAllPermissions(ctx context.Context, roleID int64) ([]model.Permission, error)
}
