package cmd

import (
	"context"
	"fmt"
	"log"
	"net"
	"os"
	"os/signal"
	"syscall"
	"time"

	"github.com/adityakw90/service-access/internal/adapter/api/grpc/handler"
	"github.com/adityakw90/service-access/internal/core/port/service"
	"google.golang.org/grpc"
)

func main() {
	// TODO: Initialize dependencies (repositories, event publisher, etc.)
	// For now, creating with nil dependencies - these will be wired up with proper DI

	// Create services - nil dependencies will be replaced with proper DI
	var permService service.PermissionService = nil
	var roleService service.RoleService = nil
	var groupService service.GroupService = nil
	var accessService service.AccessService = nil
	var subjectService service.SubjectService = nil

	// Create gRPC server
	grpcServer := grpc.NewServer(
		grpc.ChainUnaryInterceptor(
			loggingInterceptor(),
			recoveryInterceptor(),
		),
	)

	// Create handlers
	permHandler := handler.NewPermissionHandler(permService, nil)
	roleHandler := handler.NewRoleHandler(roleService, nil)
	groupHandler := handler.NewGroupHandler(groupService, nil)
	accessHandler := handler.NewAccessHandler(accessService, subjectService, nil)

	// Register services with the gRPC server
	// Note: The actual registration functions are generated by protoc
	// Uncomment when proto files are properly generated and imported:
	//
	// import (
	//     permissionpb "github.com/adityakw90/service-access-proto/gen/go/permission"
	//     rolepb "github.com/adityakw90/service-access-proto/gen/go/role"
	//     groupbp "github.com/adityakw90/service-access-proto/gen/go/group"
	//     accesspb "github.com/adityakw90/service-access-proto/gen/go/access"
	// )
	//
	// permissionpb.RegisterPermissionServiceServer(server, permHandler)
	// rolepb.RegisterRoleServiceServer(server, roleHandler)
	// groupbp.RegisterGroupServiceServer(server, groupHandler)
	// accesspb.RegisterAccessServiceServer(server, accessHandler)

	_ = permHandler
	_ = roleHandler
	_ = groupHandler
	_ = accessHandler

	// Get server address from environment or use default
	port := os.Getenv("GRPC_PORT")
	if port == "" {
		port = "50051"
	}
	address := fmt.Sprintf(":%s", port)

	// Start server in a goroutine
	errChan := make(chan error, 1)
	go func() {
		log.Printf("Starting gRPC server on %s", address)
		listener, err := net.Listen("tcp", address)
		if err != nil {
			errChan <- fmt.Errorf("failed to listen on %s: %w", address, err)
			return
		}

		if err := grpcServer.Serve(listener); err != nil {
			errChan <- fmt.Errorf("server failed: %w", err)
		}
	}()

	// Wait for interrupt signal
	sigChan := make(chan os.Signal, 1)
	signal.Notify(sigChan, syscall.SIGINT, syscall.SIGTERM)

	select {
	case err := <-errChan:
		log.Fatalf("Server error: %v", err)
	case sig := <-sigChan:
		log.Printf("Received signal %v, shutting down gracefully...", sig)
		ctx, cancel := context.WithTimeout(context.Background(), 5*time.Second)
		defer cancel()
		grpcServer.GracefulStop()
		<-ctx.Done()
		log.Println("Server stopped")
	}
}

// loggingInterceptor logs all gRPC requests
func loggingInterceptor() grpc.UnaryServerInterceptor {
	return func(ctx context.Context, req interface{}, info *grpc.UnaryServerInfo, handler grpc.UnaryHandler) (interface{}, error) {
		start := time.Now()
		log.Printf("gRPC request: %s", info.FullMethod)
		resp, err := handler(ctx, req)
		log.Printf("gRPC request completed: %s (duration: %v, error: %v)", info.FullMethod, time.Since(start), err)
		return resp, err
	}
}

// recoveryInterceptor recovers from panics in gRPC handlers
func recoveryInterceptor() grpc.UnaryServerInterceptor {
	return func(ctx context.Context, req interface{}, info *grpc.UnaryServerInfo, handler grpc.UnaryHandler) (resp interface{}, err error) {
		defer func() {
			if r := recover(); r != nil {
				log.Printf("Recovered from panic in %s: %v", info.FullMethod, r)
				err = fmt.Errorf("internal server error")
			}
		}()
		return handler(ctx, req)
	}
}
