// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	model "github.com/adityakw90/service-access/internal/core/domain/model"
	mock "github.com/stretchr/testify/mock"

	param "github.com/adityakw90/service-access/internal/core/domain/param"
)

// MockGroupService is an autogenerated mock type for the GroupService type
type MockGroupService struct {
	mock.Mock
}

type MockGroupService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockGroupService) EXPECT() *MockGroupService_Expecter {
	return &MockGroupService_Expecter{mock: &_m.Mock}
}

// AssignPermission provides a mock function with given fields: ctx, groupUID, permissionUID
func (_m *MockGroupService) AssignPermission(ctx context.Context, groupUID string, permissionUID string) error {
	ret := _m.Called(ctx, groupUID, permissionUID)

	if len(ret) == 0 {
		panic("no return value specified for AssignPermission")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = rf(ctx, groupUID, permissionUID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockGroupService_AssignPermission_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AssignPermission'
type MockGroupService_AssignPermission_Call struct {
	*mock.Call
}

// AssignPermission is a helper method to define mock.On call
//   - ctx context.Context
//   - groupUID string
//   - permissionUID string
func (_e *MockGroupService_Expecter) AssignPermission(ctx interface{}, groupUID interface{}, permissionUID interface{}) *MockGroupService_AssignPermission_Call {
	return &MockGroupService_AssignPermission_Call{Call: _e.mock.On("AssignPermission", ctx, groupUID, permissionUID)}
}

func (_c *MockGroupService_AssignPermission_Call) Run(run func(ctx context.Context, groupUID string, permissionUID string)) *MockGroupService_AssignPermission_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockGroupService_AssignPermission_Call) Return(_a0 error) *MockGroupService_AssignPermission_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockGroupService_AssignPermission_Call) RunAndReturn(run func(context.Context, string, string) error) *MockGroupService_AssignPermission_Call {
	_c.Call.Return(run)
	return _c
}

// Create provides a mock function with given fields: ctx, _a1
func (_m *MockGroupService) Create(ctx context.Context, _a1 param.GroupCreateParam) (*model.Group, error) {
	ret := _m.Called(ctx, _a1)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *model.Group
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, param.GroupCreateParam) (*model.Group, error)); ok {
		return rf(ctx, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, param.GroupCreateParam) *model.Group); ok {
		r0 = rf(ctx, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Group)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, param.GroupCreateParam) error); ok {
		r1 = rf(ctx, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockGroupService_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockGroupService_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - _a1 param.GroupCreateParam
func (_e *MockGroupService_Expecter) Create(ctx interface{}, _a1 interface{}) *MockGroupService_Create_Call {
	return &MockGroupService_Create_Call{Call: _e.mock.On("Create", ctx, _a1)}
}

func (_c *MockGroupService_Create_Call) Run(run func(ctx context.Context, _a1 param.GroupCreateParam)) *MockGroupService_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(param.GroupCreateParam))
	})
	return _c
}

func (_c *MockGroupService_Create_Call) Return(_a0 *model.Group, _a1 error) *MockGroupService_Create_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockGroupService_Create_Call) RunAndReturn(run func(context.Context, param.GroupCreateParam) (*model.Group, error)) *MockGroupService_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function with given fields: ctx, uid
func (_m *MockGroupService) Delete(ctx context.Context, uid string) error {
	ret := _m.Called(ctx, uid)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, uid)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockGroupService_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockGroupService_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - uid string
func (_e *MockGroupService_Expecter) Delete(ctx interface{}, uid interface{}) *MockGroupService_Delete_Call {
	return &MockGroupService_Delete_Call{Call: _e.mock.On("Delete", ctx, uid)}
}

func (_c *MockGroupService_Delete_Call) Run(run func(ctx context.Context, uid string)) *MockGroupService_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockGroupService_Delete_Call) Return(_a0 error) *MockGroupService_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockGroupService_Delete_Call) RunAndReturn(run func(context.Context, string) error) *MockGroupService_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function with given fields: ctx, uid
func (_m *MockGroupService) Get(ctx context.Context, uid string) (*model.Group, error) {
	ret := _m.Called(ctx, uid)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 *model.Group
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*model.Group, error)); ok {
		return rf(ctx, uid)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *model.Group); ok {
		r0 = rf(ctx, uid)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Group)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, uid)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockGroupService_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockGroupService_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - uid string
func (_e *MockGroupService_Expecter) Get(ctx interface{}, uid interface{}) *MockGroupService_Get_Call {
	return &MockGroupService_Get_Call{Call: _e.mock.On("Get", ctx, uid)}
}

func (_c *MockGroupService_Get_Call) Run(run func(ctx context.Context, uid string)) *MockGroupService_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockGroupService_Get_Call) Return(_a0 *model.Group, _a1 error) *MockGroupService_Get_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockGroupService_Get_Call) RunAndReturn(run func(context.Context, string) (*model.Group, error)) *MockGroupService_Get_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function with given fields: ctx, pagination, filter
func (_m *MockGroupService) List(ctx context.Context, pagination *param.PaginationParam, filter *param.GroupListFilterParam) (*model.Groups, error) {
	ret := _m.Called(ctx, pagination, filter)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 *model.Groups
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *param.PaginationParam, *param.GroupListFilterParam) (*model.Groups, error)); ok {
		return rf(ctx, pagination, filter)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *param.PaginationParam, *param.GroupListFilterParam) *model.Groups); ok {
		r0 = rf(ctx, pagination, filter)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Groups)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *param.PaginationParam, *param.GroupListFilterParam) error); ok {
		r1 = rf(ctx, pagination, filter)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockGroupService_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type MockGroupService_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
//   - pagination *param.PaginationParam
//   - filter *param.GroupListFilterParam
func (_e *MockGroupService_Expecter) List(ctx interface{}, pagination interface{}, filter interface{}) *MockGroupService_List_Call {
	return &MockGroupService_List_Call{Call: _e.mock.On("List", ctx, pagination, filter)}
}

func (_c *MockGroupService_List_Call) Run(run func(ctx context.Context, pagination *param.PaginationParam, filter *param.GroupListFilterParam)) *MockGroupService_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*param.PaginationParam), args[2].(*param.GroupListFilterParam))
	})
	return _c
}

func (_c *MockGroupService_List_Call) Return(_a0 *model.Groups, _a1 error) *MockGroupService_List_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockGroupService_List_Call) RunAndReturn(run func(context.Context, *param.PaginationParam, *param.GroupListFilterParam) (*model.Groups, error)) *MockGroupService_List_Call {
	_c.Call.Return(run)
	return _c
}

// ListPermission provides a mock function with given fields: ctx, groupUID, pagination, filter
func (_m *MockGroupService) ListPermission(ctx context.Context, groupUID string, pagination *param.PaginationParam, filter *param.GroupPermissionListFilterParam) (*model.GroupPermissions, error) {
	ret := _m.Called(ctx, groupUID, pagination, filter)

	if len(ret) == 0 {
		panic("no return value specified for ListPermission")
	}

	var r0 *model.GroupPermissions
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, *param.PaginationParam, *param.GroupPermissionListFilterParam) (*model.GroupPermissions, error)); ok {
		return rf(ctx, groupUID, pagination, filter)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, *param.PaginationParam, *param.GroupPermissionListFilterParam) *model.GroupPermissions); ok {
		r0 = rf(ctx, groupUID, pagination, filter)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.GroupPermissions)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, *param.PaginationParam, *param.GroupPermissionListFilterParam) error); ok {
		r1 = rf(ctx, groupUID, pagination, filter)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockGroupService_ListPermission_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListPermission'
type MockGroupService_ListPermission_Call struct {
	*mock.Call
}

// ListPermission is a helper method to define mock.On call
//   - ctx context.Context
//   - groupUID string
//   - pagination *param.PaginationParam
//   - filter *param.GroupPermissionListFilterParam
func (_e *MockGroupService_Expecter) ListPermission(ctx interface{}, groupUID interface{}, pagination interface{}, filter interface{}) *MockGroupService_ListPermission_Call {
	return &MockGroupService_ListPermission_Call{Call: _e.mock.On("ListPermission", ctx, groupUID, pagination, filter)}
}

func (_c *MockGroupService_ListPermission_Call) Run(run func(ctx context.Context, groupUID string, pagination *param.PaginationParam, filter *param.GroupPermissionListFilterParam)) *MockGroupService_ListPermission_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(*param.PaginationParam), args[3].(*param.GroupPermissionListFilterParam))
	})
	return _c
}

func (_c *MockGroupService_ListPermission_Call) Return(_a0 *model.GroupPermissions, _a1 error) *MockGroupService_ListPermission_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockGroupService_ListPermission_Call) RunAndReturn(run func(context.Context, string, *param.PaginationParam, *param.GroupPermissionListFilterParam) (*model.GroupPermissions, error)) *MockGroupService_ListPermission_Call {
	_c.Call.Return(run)
	return _c
}

// RevokePermission provides a mock function with given fields: ctx, groupUID, permissionUID
func (_m *MockGroupService) RevokePermission(ctx context.Context, groupUID string, permissionUID string) error {
	ret := _m.Called(ctx, groupUID, permissionUID)

	if len(ret) == 0 {
		panic("no return value specified for RevokePermission")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = rf(ctx, groupUID, permissionUID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockGroupService_RevokePermission_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RevokePermission'
type MockGroupService_RevokePermission_Call struct {
	*mock.Call
}

// RevokePermission is a helper method to define mock.On call
//   - ctx context.Context
//   - groupUID string
//   - permissionUID string
func (_e *MockGroupService_Expecter) RevokePermission(ctx interface{}, groupUID interface{}, permissionUID interface{}) *MockGroupService_RevokePermission_Call {
	return &MockGroupService_RevokePermission_Call{Call: _e.mock.On("RevokePermission", ctx, groupUID, permissionUID)}
}

func (_c *MockGroupService_RevokePermission_Call) Run(run func(ctx context.Context, groupUID string, permissionUID string)) *MockGroupService_RevokePermission_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockGroupService_RevokePermission_Call) Return(_a0 error) *MockGroupService_RevokePermission_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockGroupService_RevokePermission_Call) RunAndReturn(run func(context.Context, string, string) error) *MockGroupService_RevokePermission_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: ctx, uid, _a2
func (_m *MockGroupService) Update(ctx context.Context, uid string, _a2 param.GroupUpdateParam) error {
	ret := _m.Called(ctx, uid, _a2)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, param.GroupUpdateParam) error); ok {
		r0 = rf(ctx, uid, _a2)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockGroupService_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockGroupService_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - uid string
//   - _a2 param.GroupUpdateParam
func (_e *MockGroupService_Expecter) Update(ctx interface{}, uid interface{}, _a2 interface{}) *MockGroupService_Update_Call {
	return &MockGroupService_Update_Call{Call: _e.mock.On("Update", ctx, uid, _a2)}
}

func (_c *MockGroupService_Update_Call) Run(run func(ctx context.Context, uid string, _a2 param.GroupUpdateParam)) *MockGroupService_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(param.GroupUpdateParam))
	})
	return _c
}

func (_c *MockGroupService_Update_Call) Return(_a0 error) *MockGroupService_Update_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockGroupService_Update_Call) RunAndReturn(run func(context.Context, string, param.GroupUpdateParam) error) *MockGroupService_Update_Call {
	_c.Call.Return(run)
	return _c
}

// UpdatePermission provides a mock function with given fields: ctx, groupUID, permissionUID
func (_m *MockGroupService) UpdatePermission(ctx context.Context, groupUID string, permissionUID []string) error {
	ret := _m.Called(ctx, groupUID, permissionUID)

	if len(ret) == 0 {
		panic("no return value specified for UpdatePermission")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, []string) error); ok {
		r0 = rf(ctx, groupUID, permissionUID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockGroupService_UpdatePermission_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdatePermission'
type MockGroupService_UpdatePermission_Call struct {
	*mock.Call
}

// UpdatePermission is a helper method to define mock.On call
//   - ctx context.Context
//   - groupUID string
//   - permissionUID []string
func (_e *MockGroupService_Expecter) UpdatePermission(ctx interface{}, groupUID interface{}, permissionUID interface{}) *MockGroupService_UpdatePermission_Call {
	return &MockGroupService_UpdatePermission_Call{Call: _e.mock.On("UpdatePermission", ctx, groupUID, permissionUID)}
}

func (_c *MockGroupService_UpdatePermission_Call) Run(run func(ctx context.Context, groupUID string, permissionUID []string)) *MockGroupService_UpdatePermission_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].([]string))
	})
	return _c
}

func (_c *MockGroupService_UpdatePermission_Call) Return(_a0 error) *MockGroupService_UpdatePermission_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockGroupService_UpdatePermission_Call) RunAndReturn(run func(context.Context, string, []string) error) *MockGroupService_UpdatePermission_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockGroupService creates a new instance of MockGroupService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockGroupService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockGroupService {
	mock := &MockGroupService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
