// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockAccessService is an autogenerated mock type for the AccessService type
type MockAccessService struct {
	mock.Mock
}

type MockAccessService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAccessService) EXPECT() *MockAccessService_Expecter {
	return &MockAccessService_Expecter{mock: &_m.Mock}
}

// Check provides a mock function with given fields: ctx, subjectID, subjectType, resource, action
func (_m *MockAccessService) Check(ctx context.Context, subjectID string, subjectType string, resource string, action string) (bool, string, error) {
	ret := _m.Called(ctx, subjectID, subjectType, resource, action)

	if len(ret) == 0 {
		panic("no return value specified for Check")
	}

	var r0 bool
	var r1 string
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string, string) (bool, string, error)); ok {
		return rf(ctx, subjectID, subjectType, resource, action)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string, string) bool); ok {
		r0 = rf(ctx, subjectID, subjectType, resource, action)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, string, string) string); ok {
		r1 = rf(ctx, subjectID, subjectType, resource, action)
	} else {
		r1 = ret.Get(1).(string)
	}

	if rf, ok := ret.Get(2).(func(context.Context, string, string, string, string) error); ok {
		r2 = rf(ctx, subjectID, subjectType, resource, action)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// MockAccessService_Check_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Check'
type MockAccessService_Check_Call struct {
	*mock.Call
}

// Check is a helper method to define mock.On call
//   - ctx context.Context
//   - subjectID string
//   - subjectType string
//   - resource string
//   - action string
func (_e *MockAccessService_Expecter) Check(ctx interface{}, subjectID interface{}, subjectType interface{}, resource interface{}, action interface{}) *MockAccessService_Check_Call {
	return &MockAccessService_Check_Call{Call: _e.mock.On("Check", ctx, subjectID, subjectType, resource, action)}
}

func (_c *MockAccessService_Check_Call) Run(run func(ctx context.Context, subjectID string, subjectType string, resource string, action string)) *MockAccessService_Check_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(string), args[4].(string))
	})
	return _c
}

func (_c *MockAccessService_Check_Call) Return(allowed bool, reason string, err error) *MockAccessService_Check_Call {
	_c.Call.Return(allowed, reason, err)
	return _c
}

func (_c *MockAccessService_Check_Call) RunAndReturn(run func(context.Context, string, string, string, string) (bool, string, error)) *MockAccessService_Check_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockAccessService creates a new instance of MockAccessService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAccessService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAccessService {
	mock := &MockAccessService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
