// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	model "github.com/adityakw90/service-access/internal/core/domain/model"
	mock "github.com/stretchr/testify/mock"

	param "github.com/adityakw90/service-access/internal/core/domain/param"
)

// MockRoleService is an autogenerated mock type for the RoleService type
type MockRoleService struct {
	mock.Mock
}

type MockRoleService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRoleService) EXPECT() *MockRoleService_Expecter {
	return &MockRoleService_Expecter{mock: &_m.Mock}
}

// AssignPermission provides a mock function with given fields: ctx, roleUID, permissionUID
func (_m *MockRoleService) AssignPermission(ctx context.Context, roleUID string, permissionUID string) error {
	ret := _m.Called(ctx, roleUID, permissionUID)

	if len(ret) == 0 {
		panic("no return value specified for AssignPermission")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = rf(ctx, roleUID, permissionUID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockRoleService_AssignPermission_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AssignPermission'
type MockRoleService_AssignPermission_Call struct {
	*mock.Call
}

// AssignPermission is a helper method to define mock.On call
//   - ctx context.Context
//   - roleUID string
//   - permissionUID string
func (_e *MockRoleService_Expecter) AssignPermission(ctx interface{}, roleUID interface{}, permissionUID interface{}) *MockRoleService_AssignPermission_Call {
	return &MockRoleService_AssignPermission_Call{Call: _e.mock.On("AssignPermission", ctx, roleUID, permissionUID)}
}

func (_c *MockRoleService_AssignPermission_Call) Run(run func(ctx context.Context, roleUID string, permissionUID string)) *MockRoleService_AssignPermission_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockRoleService_AssignPermission_Call) Return(_a0 error) *MockRoleService_AssignPermission_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockRoleService_AssignPermission_Call) RunAndReturn(run func(context.Context, string, string) error) *MockRoleService_AssignPermission_Call {
	_c.Call.Return(run)
	return _c
}

// Create provides a mock function with given fields: ctx, _a1
func (_m *MockRoleService) Create(ctx context.Context, _a1 param.RoleCreateParam) (*model.Role, error) {
	ret := _m.Called(ctx, _a1)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *model.Role
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, param.RoleCreateParam) (*model.Role, error)); ok {
		return rf(ctx, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, param.RoleCreateParam) *model.Role); ok {
		r0 = rf(ctx, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Role)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, param.RoleCreateParam) error); ok {
		r1 = rf(ctx, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRoleService_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockRoleService_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - _a1 param.RoleCreateParam
func (_e *MockRoleService_Expecter) Create(ctx interface{}, _a1 interface{}) *MockRoleService_Create_Call {
	return &MockRoleService_Create_Call{Call: _e.mock.On("Create", ctx, _a1)}
}

func (_c *MockRoleService_Create_Call) Run(run func(ctx context.Context, _a1 param.RoleCreateParam)) *MockRoleService_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(param.RoleCreateParam))
	})
	return _c
}

func (_c *MockRoleService_Create_Call) Return(_a0 *model.Role, _a1 error) *MockRoleService_Create_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRoleService_Create_Call) RunAndReturn(run func(context.Context, param.RoleCreateParam) (*model.Role, error)) *MockRoleService_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function with given fields: ctx, uid
func (_m *MockRoleService) Delete(ctx context.Context, uid string) error {
	ret := _m.Called(ctx, uid)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, uid)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockRoleService_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockRoleService_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - uid string
func (_e *MockRoleService_Expecter) Delete(ctx interface{}, uid interface{}) *MockRoleService_Delete_Call {
	return &MockRoleService_Delete_Call{Call: _e.mock.On("Delete", ctx, uid)}
}

func (_c *MockRoleService_Delete_Call) Run(run func(ctx context.Context, uid string)) *MockRoleService_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockRoleService_Delete_Call) Return(_a0 error) *MockRoleService_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockRoleService_Delete_Call) RunAndReturn(run func(context.Context, string) error) *MockRoleService_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function with given fields: ctx, uid
func (_m *MockRoleService) Get(ctx context.Context, uid string) (*model.Role, error) {
	ret := _m.Called(ctx, uid)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 *model.Role
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*model.Role, error)); ok {
		return rf(ctx, uid)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *model.Role); ok {
		r0 = rf(ctx, uid)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Role)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, uid)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRoleService_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockRoleService_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - uid string
func (_e *MockRoleService_Expecter) Get(ctx interface{}, uid interface{}) *MockRoleService_Get_Call {
	return &MockRoleService_Get_Call{Call: _e.mock.On("Get", ctx, uid)}
}

func (_c *MockRoleService_Get_Call) Run(run func(ctx context.Context, uid string)) *MockRoleService_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockRoleService_Get_Call) Return(_a0 *model.Role, _a1 error) *MockRoleService_Get_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRoleService_Get_Call) RunAndReturn(run func(context.Context, string) (*model.Role, error)) *MockRoleService_Get_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function with given fields: ctx, pagination, filter
func (_m *MockRoleService) List(ctx context.Context, pagination *param.PaginationParam, filter *param.RoleListFilterParam) (*model.Roles, error) {
	ret := _m.Called(ctx, pagination, filter)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 *model.Roles
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *param.PaginationParam, *param.RoleListFilterParam) (*model.Roles, error)); ok {
		return rf(ctx, pagination, filter)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *param.PaginationParam, *param.RoleListFilterParam) *model.Roles); ok {
		r0 = rf(ctx, pagination, filter)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Roles)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *param.PaginationParam, *param.RoleListFilterParam) error); ok {
		r1 = rf(ctx, pagination, filter)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRoleService_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type MockRoleService_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
//   - pagination *param.PaginationParam
//   - filter *param.RoleListFilterParam
func (_e *MockRoleService_Expecter) List(ctx interface{}, pagination interface{}, filter interface{}) *MockRoleService_List_Call {
	return &MockRoleService_List_Call{Call: _e.mock.On("List", ctx, pagination, filter)}
}

func (_c *MockRoleService_List_Call) Run(run func(ctx context.Context, pagination *param.PaginationParam, filter *param.RoleListFilterParam)) *MockRoleService_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*param.PaginationParam), args[2].(*param.RoleListFilterParam))
	})
	return _c
}

func (_c *MockRoleService_List_Call) Return(_a0 *model.Roles, _a1 error) *MockRoleService_List_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRoleService_List_Call) RunAndReturn(run func(context.Context, *param.PaginationParam, *param.RoleListFilterParam) (*model.Roles, error)) *MockRoleService_List_Call {
	_c.Call.Return(run)
	return _c
}

// ListPermission provides a mock function with given fields: ctx, roleUID, pagination, filter
func (_m *MockRoleService) ListPermission(ctx context.Context, roleUID string, pagination *param.PaginationParam, filter *param.RolePermissionListFilterParam) (*model.RolePermissions, error) {
	ret := _m.Called(ctx, roleUID, pagination, filter)

	if len(ret) == 0 {
		panic("no return value specified for ListPermission")
	}

	var r0 *model.RolePermissions
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, *param.PaginationParam, *param.RolePermissionListFilterParam) (*model.RolePermissions, error)); ok {
		return rf(ctx, roleUID, pagination, filter)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, *param.PaginationParam, *param.RolePermissionListFilterParam) *model.RolePermissions); ok {
		r0 = rf(ctx, roleUID, pagination, filter)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.RolePermissions)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, *param.PaginationParam, *param.RolePermissionListFilterParam) error); ok {
		r1 = rf(ctx, roleUID, pagination, filter)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRoleService_ListPermission_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListPermission'
type MockRoleService_ListPermission_Call struct {
	*mock.Call
}

// ListPermission is a helper method to define mock.On call
//   - ctx context.Context
//   - roleUID string
//   - pagination *param.PaginationParam
//   - filter *param.RolePermissionListFilterParam
func (_e *MockRoleService_Expecter) ListPermission(ctx interface{}, roleUID interface{}, pagination interface{}, filter interface{}) *MockRoleService_ListPermission_Call {
	return &MockRoleService_ListPermission_Call{Call: _e.mock.On("ListPermission", ctx, roleUID, pagination, filter)}
}

func (_c *MockRoleService_ListPermission_Call) Run(run func(ctx context.Context, roleUID string, pagination *param.PaginationParam, filter *param.RolePermissionListFilterParam)) *MockRoleService_ListPermission_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(*param.PaginationParam), args[3].(*param.RolePermissionListFilterParam))
	})
	return _c
}

func (_c *MockRoleService_ListPermission_Call) Return(_a0 *model.RolePermissions, _a1 error) *MockRoleService_ListPermission_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRoleService_ListPermission_Call) RunAndReturn(run func(context.Context, string, *param.PaginationParam, *param.RolePermissionListFilterParam) (*model.RolePermissions, error)) *MockRoleService_ListPermission_Call {
	_c.Call.Return(run)
	return _c
}

// RevokePermission provides a mock function with given fields: ctx, roleUID, permissionUID
func (_m *MockRoleService) RevokePermission(ctx context.Context, roleUID string, permissionUID string) error {
	ret := _m.Called(ctx, roleUID, permissionUID)

	if len(ret) == 0 {
		panic("no return value specified for RevokePermission")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = rf(ctx, roleUID, permissionUID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockRoleService_RevokePermission_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RevokePermission'
type MockRoleService_RevokePermission_Call struct {
	*mock.Call
}

// RevokePermission is a helper method to define mock.On call
//   - ctx context.Context
//   - roleUID string
//   - permissionUID string
func (_e *MockRoleService_Expecter) RevokePermission(ctx interface{}, roleUID interface{}, permissionUID interface{}) *MockRoleService_RevokePermission_Call {
	return &MockRoleService_RevokePermission_Call{Call: _e.mock.On("RevokePermission", ctx, roleUID, permissionUID)}
}

func (_c *MockRoleService_RevokePermission_Call) Run(run func(ctx context.Context, roleUID string, permissionUID string)) *MockRoleService_RevokePermission_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockRoleService_RevokePermission_Call) Return(_a0 error) *MockRoleService_RevokePermission_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockRoleService_RevokePermission_Call) RunAndReturn(run func(context.Context, string, string) error) *MockRoleService_RevokePermission_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: ctx, uid, _a2
func (_m *MockRoleService) Update(ctx context.Context, uid string, _a2 param.RoleUpdateParam) error {
	ret := _m.Called(ctx, uid, _a2)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, param.RoleUpdateParam) error); ok {
		r0 = rf(ctx, uid, _a2)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockRoleService_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockRoleService_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - uid string
//   - _a2 param.RoleUpdateParam
func (_e *MockRoleService_Expecter) Update(ctx interface{}, uid interface{}, _a2 interface{}) *MockRoleService_Update_Call {
	return &MockRoleService_Update_Call{Call: _e.mock.On("Update", ctx, uid, _a2)}
}

func (_c *MockRoleService_Update_Call) Run(run func(ctx context.Context, uid string, _a2 param.RoleUpdateParam)) *MockRoleService_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(param.RoleUpdateParam))
	})
	return _c
}

func (_c *MockRoleService_Update_Call) Return(_a0 error) *MockRoleService_Update_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockRoleService_Update_Call) RunAndReturn(run func(context.Context, string, param.RoleUpdateParam) error) *MockRoleService_Update_Call {
	_c.Call.Return(run)
	return _c
}

// UpdatePermission provides a mock function with given fields: ctx, roleUID, permissionUID
func (_m *MockRoleService) UpdatePermission(ctx context.Context, roleUID string, permissionUID []string) error {
	ret := _m.Called(ctx, roleUID, permissionUID)

	if len(ret) == 0 {
		panic("no return value specified for UpdatePermission")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, []string) error); ok {
		r0 = rf(ctx, roleUID, permissionUID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockRoleService_UpdatePermission_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdatePermission'
type MockRoleService_UpdatePermission_Call struct {
	*mock.Call
}

// UpdatePermission is a helper method to define mock.On call
//   - ctx context.Context
//   - roleUID string
//   - permissionUID []string
func (_e *MockRoleService_Expecter) UpdatePermission(ctx interface{}, roleUID interface{}, permissionUID interface{}) *MockRoleService_UpdatePermission_Call {
	return &MockRoleService_UpdatePermission_Call{Call: _e.mock.On("UpdatePermission", ctx, roleUID, permissionUID)}
}

func (_c *MockRoleService_UpdatePermission_Call) Run(run func(ctx context.Context, roleUID string, permissionUID []string)) *MockRoleService_UpdatePermission_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].([]string))
	})
	return _c
}

func (_c *MockRoleService_UpdatePermission_Call) Return(_a0 error) *MockRoleService_UpdatePermission_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockRoleService_UpdatePermission_Call) RunAndReturn(run func(context.Context, string, []string) error) *MockRoleService_UpdatePermission_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockRoleService creates a new instance of MockRoleService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRoleService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRoleService {
	mock := &MockRoleService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
