// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	model "github.com/adityakw90/service-access/internal/core/domain/model"
	mock "github.com/stretchr/testify/mock"

	param "github.com/adityakw90/service-access/internal/core/domain/param"
)

// MockPermissionService is an autogenerated mock type for the PermissionService type
type MockPermissionService struct {
	mock.Mock
}

type MockPermissionService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockPermissionService) EXPECT() *MockPermissionService_Expecter {
	return &MockPermissionService_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, _a1
func (_m *MockPermissionService) Create(ctx context.Context, _a1 param.PermissionCreateParam) (*model.Permission, error) {
	ret := _m.Called(ctx, _a1)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *model.Permission
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, param.PermissionCreateParam) (*model.Permission, error)); ok {
		return rf(ctx, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, param.PermissionCreateParam) *model.Permission); ok {
		r0 = rf(ctx, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Permission)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, param.PermissionCreateParam) error); ok {
		r1 = rf(ctx, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockPermissionService_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockPermissionService_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - _a1 param.PermissionCreateParam
func (_e *MockPermissionService_Expecter) Create(ctx interface{}, _a1 interface{}) *MockPermissionService_Create_Call {
	return &MockPermissionService_Create_Call{Call: _e.mock.On("Create", ctx, _a1)}
}

func (_c *MockPermissionService_Create_Call) Run(run func(ctx context.Context, _a1 param.PermissionCreateParam)) *MockPermissionService_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(param.PermissionCreateParam))
	})
	return _c
}

func (_c *MockPermissionService_Create_Call) Return(_a0 *model.Permission, _a1 error) *MockPermissionService_Create_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockPermissionService_Create_Call) RunAndReturn(run func(context.Context, param.PermissionCreateParam) (*model.Permission, error)) *MockPermissionService_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function with given fields: ctx, uid
func (_m *MockPermissionService) Delete(ctx context.Context, uid string) error {
	ret := _m.Called(ctx, uid)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, uid)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockPermissionService_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockPermissionService_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - uid string
func (_e *MockPermissionService_Expecter) Delete(ctx interface{}, uid interface{}) *MockPermissionService_Delete_Call {
	return &MockPermissionService_Delete_Call{Call: _e.mock.On("Delete", ctx, uid)}
}

func (_c *MockPermissionService_Delete_Call) Run(run func(ctx context.Context, uid string)) *MockPermissionService_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockPermissionService_Delete_Call) Return(_a0 error) *MockPermissionService_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockPermissionService_Delete_Call) RunAndReturn(run func(context.Context, string) error) *MockPermissionService_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function with given fields: ctx, uid
func (_m *MockPermissionService) Get(ctx context.Context, uid string) (*model.Permission, error) {
	ret := _m.Called(ctx, uid)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 *model.Permission
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*model.Permission, error)); ok {
		return rf(ctx, uid)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *model.Permission); ok {
		r0 = rf(ctx, uid)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Permission)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, uid)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockPermissionService_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockPermissionService_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - uid string
func (_e *MockPermissionService_Expecter) Get(ctx interface{}, uid interface{}) *MockPermissionService_Get_Call {
	return &MockPermissionService_Get_Call{Call: _e.mock.On("Get", ctx, uid)}
}

func (_c *MockPermissionService_Get_Call) Run(run func(ctx context.Context, uid string)) *MockPermissionService_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockPermissionService_Get_Call) Return(_a0 *model.Permission, _a1 error) *MockPermissionService_Get_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockPermissionService_Get_Call) RunAndReturn(run func(context.Context, string) (*model.Permission, error)) *MockPermissionService_Get_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function with given fields: ctx, pagination, filter
func (_m *MockPermissionService) List(ctx context.Context, pagination *param.PaginationParam, filter *param.PermissionListFilterParam) (*model.Permissions, error) {
	ret := _m.Called(ctx, pagination, filter)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 *model.Permissions
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *param.PaginationParam, *param.PermissionListFilterParam) (*model.Permissions, error)); ok {
		return rf(ctx, pagination, filter)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *param.PaginationParam, *param.PermissionListFilterParam) *model.Permissions); ok {
		r0 = rf(ctx, pagination, filter)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Permissions)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *param.PaginationParam, *param.PermissionListFilterParam) error); ok {
		r1 = rf(ctx, pagination, filter)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockPermissionService_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type MockPermissionService_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
//   - pagination *param.PaginationParam
//   - filter *param.PermissionListFilterParam
func (_e *MockPermissionService_Expecter) List(ctx interface{}, pagination interface{}, filter interface{}) *MockPermissionService_List_Call {
	return &MockPermissionService_List_Call{Call: _e.mock.On("List", ctx, pagination, filter)}
}

func (_c *MockPermissionService_List_Call) Run(run func(ctx context.Context, pagination *param.PaginationParam, filter *param.PermissionListFilterParam)) *MockPermissionService_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*param.PaginationParam), args[2].(*param.PermissionListFilterParam))
	})
	return _c
}

func (_c *MockPermissionService_List_Call) Return(_a0 *model.Permissions, _a1 error) *MockPermissionService_List_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockPermissionService_List_Call) RunAndReturn(run func(context.Context, *param.PaginationParam, *param.PermissionListFilterParam) (*model.Permissions, error)) *MockPermissionService_List_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: ctx, uid, _a2
func (_m *MockPermissionService) Update(ctx context.Context, uid string, _a2 param.PermissionUpdateParam) error {
	ret := _m.Called(ctx, uid, _a2)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, param.PermissionUpdateParam) error); ok {
		r0 = rf(ctx, uid, _a2)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockPermissionService_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockPermissionService_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - uid string
//   - _a2 param.PermissionUpdateParam
func (_e *MockPermissionService_Expecter) Update(ctx interface{}, uid interface{}, _a2 interface{}) *MockPermissionService_Update_Call {
	return &MockPermissionService_Update_Call{Call: _e.mock.On("Update", ctx, uid, _a2)}
}

func (_c *MockPermissionService_Update_Call) Run(run func(ctx context.Context, uid string, _a2 param.PermissionUpdateParam)) *MockPermissionService_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(param.PermissionUpdateParam))
	})
	return _c
}

func (_c *MockPermissionService_Update_Call) Return(_a0 error) *MockPermissionService_Update_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockPermissionService_Update_Call) RunAndReturn(run func(context.Context, string, param.PermissionUpdateParam) error) *MockPermissionService_Update_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockPermissionService creates a new instance of MockPermissionService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockPermissionService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockPermissionService {
	mock := &MockPermissionService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
