// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	model "github.com/adityakw90/service-access/internal/core/domain/model"
	mock "github.com/stretchr/testify/mock"

	param "github.com/adityakw90/service-access/internal/core/domain/param"
)

// MockSubjectService is an autogenerated mock type for the SubjectService type
type MockSubjectService struct {
	mock.Mock
}

type MockSubjectService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockSubjectService) EXPECT() *MockSubjectService_Expecter {
	return &MockSubjectService_Expecter{mock: &_m.Mock}
}

// Assign provides a mock function with given fields: ctx, subjectID, subjectType, roleUID
func (_m *MockSubjectService) Assign(ctx context.Context, subjectID string, subjectType string, roleUID string) error {
	ret := _m.Called(ctx, subjectID, subjectType, roleUID)

	if len(ret) == 0 {
		panic("no return value specified for Assign")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string) error); ok {
		r0 = rf(ctx, subjectID, subjectType, roleUID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockSubjectService_Assign_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Assign'
type MockSubjectService_Assign_Call struct {
	*mock.Call
}

// Assign is a helper method to define mock.On call
//   - ctx context.Context
//   - subjectID string
//   - subjectType string
//   - roleUID string
func (_e *MockSubjectService_Expecter) Assign(ctx interface{}, subjectID interface{}, subjectType interface{}, roleUID interface{}) *MockSubjectService_Assign_Call {
	return &MockSubjectService_Assign_Call{Call: _e.mock.On("Assign", ctx, subjectID, subjectType, roleUID)}
}

func (_c *MockSubjectService_Assign_Call) Run(run func(ctx context.Context, subjectID string, subjectType string, roleUID string)) *MockSubjectService_Assign_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(string))
	})
	return _c
}

func (_c *MockSubjectService_Assign_Call) Return(_a0 error) *MockSubjectService_Assign_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockSubjectService_Assign_Call) RunAndReturn(run func(context.Context, string, string, string) error) *MockSubjectService_Assign_Call {
	_c.Call.Return(run)
	return _c
}

// GetFullProfile provides a mock function with given fields: ctx, subjectID, subjectType
func (_m *MockSubjectService) GetFullProfile(ctx context.Context, subjectID string, subjectType string) (*model.SubjectProfile, error) {
	ret := _m.Called(ctx, subjectID, subjectType)

	if len(ret) == 0 {
		panic("no return value specified for GetFullProfile")
	}

	var r0 *model.SubjectProfile
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (*model.SubjectProfile, error)); ok {
		return rf(ctx, subjectID, subjectType)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) *model.SubjectProfile); ok {
		r0 = rf(ctx, subjectID, subjectType)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.SubjectProfile)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, subjectID, subjectType)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockSubjectService_GetFullProfile_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetFullProfile'
type MockSubjectService_GetFullProfile_Call struct {
	*mock.Call
}

// GetFullProfile is a helper method to define mock.On call
//   - ctx context.Context
//   - subjectID string
//   - subjectType string
func (_e *MockSubjectService_Expecter) GetFullProfile(ctx interface{}, subjectID interface{}, subjectType interface{}) *MockSubjectService_GetFullProfile_Call {
	return &MockSubjectService_GetFullProfile_Call{Call: _e.mock.On("GetFullProfile", ctx, subjectID, subjectType)}
}

func (_c *MockSubjectService_GetFullProfile_Call) Run(run func(ctx context.Context, subjectID string, subjectType string)) *MockSubjectService_GetFullProfile_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockSubjectService_GetFullProfile_Call) Return(_a0 *model.SubjectProfile, _a1 error) *MockSubjectService_GetFullProfile_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockSubjectService_GetFullProfile_Call) RunAndReturn(run func(context.Context, string, string) (*model.SubjectProfile, error)) *MockSubjectService_GetFullProfile_Call {
	_c.Call.Return(run)
	return _c
}

// GetGroups provides a mock function with given fields: ctx, subjectID, subjectType
func (_m *MockSubjectService) GetGroups(ctx context.Context, subjectID string, subjectType string) ([]model.Group, error) {
	ret := _m.Called(ctx, subjectID, subjectType)

	if len(ret) == 0 {
		panic("no return value specified for GetGroups")
	}

	var r0 []model.Group
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) ([]model.Group, error)); ok {
		return rf(ctx, subjectID, subjectType)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) []model.Group); ok {
		r0 = rf(ctx, subjectID, subjectType)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.Group)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, subjectID, subjectType)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockSubjectService_GetGroups_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetGroups'
type MockSubjectService_GetGroups_Call struct {
	*mock.Call
}

// GetGroups is a helper method to define mock.On call
//   - ctx context.Context
//   - subjectID string
//   - subjectType string
func (_e *MockSubjectService_Expecter) GetGroups(ctx interface{}, subjectID interface{}, subjectType interface{}) *MockSubjectService_GetGroups_Call {
	return &MockSubjectService_GetGroups_Call{Call: _e.mock.On("GetGroups", ctx, subjectID, subjectType)}
}

func (_c *MockSubjectService_GetGroups_Call) Run(run func(ctx context.Context, subjectID string, subjectType string)) *MockSubjectService_GetGroups_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockSubjectService_GetGroups_Call) Return(_a0 []model.Group, _a1 error) *MockSubjectService_GetGroups_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockSubjectService_GetGroups_Call) RunAndReturn(run func(context.Context, string, string) ([]model.Group, error)) *MockSubjectService_GetGroups_Call {
	_c.Call.Return(run)
	return _c
}

// GetPermissions provides a mock function with given fields: ctx, subjectID, subjectType
func (_m *MockSubjectService) GetPermissions(ctx context.Context, subjectID string, subjectType string) ([]model.Permission, error) {
	ret := _m.Called(ctx, subjectID, subjectType)

	if len(ret) == 0 {
		panic("no return value specified for GetPermissions")
	}

	var r0 []model.Permission
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) ([]model.Permission, error)); ok {
		return rf(ctx, subjectID, subjectType)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) []model.Permission); ok {
		r0 = rf(ctx, subjectID, subjectType)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.Permission)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, subjectID, subjectType)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockSubjectService_GetPermissions_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetPermissions'
type MockSubjectService_GetPermissions_Call struct {
	*mock.Call
}

// GetPermissions is a helper method to define mock.On call
//   - ctx context.Context
//   - subjectID string
//   - subjectType string
func (_e *MockSubjectService_Expecter) GetPermissions(ctx interface{}, subjectID interface{}, subjectType interface{}) *MockSubjectService_GetPermissions_Call {
	return &MockSubjectService_GetPermissions_Call{Call: _e.mock.On("GetPermissions", ctx, subjectID, subjectType)}
}

func (_c *MockSubjectService_GetPermissions_Call) Run(run func(ctx context.Context, subjectID string, subjectType string)) *MockSubjectService_GetPermissions_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockSubjectService_GetPermissions_Call) Return(_a0 []model.Permission, _a1 error) *MockSubjectService_GetPermissions_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockSubjectService_GetPermissions_Call) RunAndReturn(run func(context.Context, string, string) ([]model.Permission, error)) *MockSubjectService_GetPermissions_Call {
	_c.Call.Return(run)
	return _c
}

// GetRoles provides a mock function with given fields: ctx, subjectID, subjectType
func (_m *MockSubjectService) GetRoles(ctx context.Context, subjectID string, subjectType string) ([]model.Role, error) {
	ret := _m.Called(ctx, subjectID, subjectType)

	if len(ret) == 0 {
		panic("no return value specified for GetRoles")
	}

	var r0 []model.Role
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) ([]model.Role, error)); ok {
		return rf(ctx, subjectID, subjectType)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) []model.Role); ok {
		r0 = rf(ctx, subjectID, subjectType)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.Role)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, subjectID, subjectType)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockSubjectService_GetRoles_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetRoles'
type MockSubjectService_GetRoles_Call struct {
	*mock.Call
}

// GetRoles is a helper method to define mock.On call
//   - ctx context.Context
//   - subjectID string
//   - subjectType string
func (_e *MockSubjectService_Expecter) GetRoles(ctx interface{}, subjectID interface{}, subjectType interface{}) *MockSubjectService_GetRoles_Call {
	return &MockSubjectService_GetRoles_Call{Call: _e.mock.On("GetRoles", ctx, subjectID, subjectType)}
}

func (_c *MockSubjectService_GetRoles_Call) Run(run func(ctx context.Context, subjectID string, subjectType string)) *MockSubjectService_GetRoles_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockSubjectService_GetRoles_Call) Return(_a0 []model.Role, _a1 error) *MockSubjectService_GetRoles_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockSubjectService_GetRoles_Call) RunAndReturn(run func(context.Context, string, string) ([]model.Role, error)) *MockSubjectService_GetRoles_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function with given fields: ctx, pagination, filter
func (_m *MockSubjectService) List(ctx context.Context, pagination *param.PaginationParam, filter *param.SubjectListFilterParam) (*model.SubjectRoles, error) {
	ret := _m.Called(ctx, pagination, filter)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 *model.SubjectRoles
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *param.PaginationParam, *param.SubjectListFilterParam) (*model.SubjectRoles, error)); ok {
		return rf(ctx, pagination, filter)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *param.PaginationParam, *param.SubjectListFilterParam) *model.SubjectRoles); ok {
		r0 = rf(ctx, pagination, filter)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.SubjectRoles)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *param.PaginationParam, *param.SubjectListFilterParam) error); ok {
		r1 = rf(ctx, pagination, filter)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockSubjectService_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type MockSubjectService_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
//   - pagination *param.PaginationParam
//   - filter *param.SubjectListFilterParam
func (_e *MockSubjectService_Expecter) List(ctx interface{}, pagination interface{}, filter interface{}) *MockSubjectService_List_Call {
	return &MockSubjectService_List_Call{Call: _e.mock.On("List", ctx, pagination, filter)}
}

func (_c *MockSubjectService_List_Call) Run(run func(ctx context.Context, pagination *param.PaginationParam, filter *param.SubjectListFilterParam)) *MockSubjectService_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*param.PaginationParam), args[2].(*param.SubjectListFilterParam))
	})
	return _c
}

func (_c *MockSubjectService_List_Call) Return(_a0 *model.SubjectRoles, _a1 error) *MockSubjectService_List_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockSubjectService_List_Call) RunAndReturn(run func(context.Context, *param.PaginationParam, *param.SubjectListFilterParam) (*model.SubjectRoles, error)) *MockSubjectService_List_Call {
	_c.Call.Return(run)
	return _c
}

// Revoke provides a mock function with given fields: ctx, subjectID, subjectType, roleUID
func (_m *MockSubjectService) Revoke(ctx context.Context, subjectID string, subjectType string, roleUID string) error {
	ret := _m.Called(ctx, subjectID, subjectType, roleUID)

	if len(ret) == 0 {
		panic("no return value specified for Revoke")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string) error); ok {
		r0 = rf(ctx, subjectID, subjectType, roleUID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockSubjectService_Revoke_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Revoke'
type MockSubjectService_Revoke_Call struct {
	*mock.Call
}

// Revoke is a helper method to define mock.On call
//   - ctx context.Context
//   - subjectID string
//   - subjectType string
//   - roleUID string
func (_e *MockSubjectService_Expecter) Revoke(ctx interface{}, subjectID interface{}, subjectType interface{}, roleUID interface{}) *MockSubjectService_Revoke_Call {
	return &MockSubjectService_Revoke_Call{Call: _e.mock.On("Revoke", ctx, subjectID, subjectType, roleUID)}
}

func (_c *MockSubjectService_Revoke_Call) Run(run func(ctx context.Context, subjectID string, subjectType string, roleUID string)) *MockSubjectService_Revoke_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(string))
	})
	return _c
}

func (_c *MockSubjectService_Revoke_Call) Return(_a0 error) *MockSubjectService_Revoke_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockSubjectService_Revoke_Call) RunAndReturn(run func(context.Context, string, string, string) error) *MockSubjectService_Revoke_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockSubjectService creates a new instance of MockSubjectService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockSubjectService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSubjectService {
	mock := &MockSubjectService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
