// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	portResolver "github.com/adityakw90/service-access/internal/core/port/resolver"
	mock "github.com/stretchr/testify/mock"
)

// MockGroupResolver is an autogenerated mock type for the GroupResolver type
type MockGroupResolver struct {
	mock.Mock
}

type MockGroupResolver_Expecter struct {
	mock *mock.Mock
}

func (_m *MockGroupResolver) EXPECT() *MockGroupResolver_Expecter {
	return &MockGroupResolver_Expecter{mock: &_m.Mock}
}

// IDsByUIDs provides a mock function with given fields: ctx, uids
func (_m *MockGroupResolver) IDsByUIDs(ctx context.Context, uids []string) (map[string]int64, error) {
	ret := _m.Called(ctx, uids)

	if len(ret) == 0 {
		panic("no return value specified for IDsByUIDs")
	}

	var r0 map[string]int64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, []string) (map[string]int64, error)); ok {
		return rf(ctx, uids)
	}
	if rf, ok := ret.Get(0).(func(context.Context, []string) map[string]int64); ok {
		r0 = rf(ctx, uids)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]int64)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, []string) error); ok {
		r1 = rf(ctx, uids)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockGroupResolver_IDsByUIDs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IDsByUIDs'
type MockGroupResolver_IDsByUIDs_Call struct {
	*mock.Call
}

// IDsByUIDs is a helper method to define mock.On call
//   - ctx context.Context
//   - uids []string
func (_e *MockGroupResolver_Expecter) IDsByUIDs(ctx interface{}, uids interface{}) *MockGroupResolver_IDsByUIDs_Call {
	return &MockGroupResolver_IDsByUIDs_Call{Call: _e.mock.On("IDsByUIDs", ctx, uids)}
}

func (_c *MockGroupResolver_IDsByUIDs_Call) Run(run func(ctx context.Context, uids []string)) *MockGroupResolver_IDsByUIDs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].([]string))
	})
	return _c
}

func (_c *MockGroupResolver_IDsByUIDs_Call) Return(_a0 map[string]int64, _a1 error) *MockGroupResolver_IDsByUIDs_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockGroupResolver_IDsByUIDs_Call) RunAndReturn(run func(context.Context, []string) (map[string]int64, error)) *MockGroupResolver_IDsByUIDs_Call {
	_c.Call.Return(run)
	return _c
}

// UIDsByIDs provides a mock function with given fields: ctx, ids
func (_m *MockGroupResolver) UIDsByIDs(ctx context.Context, ids []int64) (map[int64]string, error) {
	ret := _m.Called(ctx, ids)

	if len(ret) == 0 {
		panic("no return value specified for UIDsByIDs")
	}

	var r0 map[int64]string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, []int64) (map[int64]string, error)); ok {
		return rf(ctx, ids)
	}
	if rf, ok := ret.Get(0).(func(context.Context, []int64) map[int64]string); ok {
		r0 = rf(ctx, ids)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[int64]string)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, []int64) error); ok {
		r1 = rf(ctx, ids)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockGroupResolver_UIDsByIDs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UIDsByIDs'
type MockGroupResolver_UIDsByIDs_Call struct {
	*mock.Call
}

// UIDsByIDs is a helper method to define mock.On call
//   - ctx context.Context
//   - ids []int64
func (_e *MockGroupResolver_Expecter) UIDsByIDs(ctx interface{}, ids interface{}) *MockGroupResolver_UIDsByIDs_Call {
	return &MockGroupResolver_UIDsByIDs_Call{Call: _e.mock.On("UIDsByIDs", ctx, ids)}
}

func (_c *MockGroupResolver_UIDsByIDs_Call) Run(run func(ctx context.Context, ids []int64)) *MockGroupResolver_UIDsByIDs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].([]int64))
	})
	return _c
}

func (_c *MockGroupResolver_UIDsByIDs_Call) Return(_a0 map[int64]string, _a1 error) *MockGroupResolver_UIDsByIDs_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockGroupResolver_UIDsByIDs_Call) RunAndReturn(run func(context.Context, []int64) (map[int64]string, error)) *MockGroupResolver_UIDsByIDs_Call {
	_c.Call.Return(run)
	return _c
}

// Invalidate provides a mock function with given fields: ctx, opts
func (_m *MockGroupResolver) Invalidate(ctx context.Context, opts ...portResolver.InvalidateOpt) error {
	ret := _m.Called(ctx, opts)

	if len(ret) == 0 {
		panic("no return value specified for Invalidate")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, []portResolver.InvalidateOpt) error); ok {
		return rf(ctx, opts)
	}
	if rf, ok := ret.Get(0).(func(...portResolver.InvalidateOpt) error); ok {
		return rf(opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(error)
		}
	}

	return r0
}

// MockGroupResolver_Invalidate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Invalidate'
type MockGroupResolver_Invalidate_Call struct {
	*mock.Call
}

// Invalidate is a helper method to define mock.On call
//   - ctx context.Context
//   - opts ...portResolver.InvalidateOpt
func (_e *MockGroupResolver_Expecter) Invalidate(ctx interface{}, opts ...interface{}) *MockGroupResolver_Invalidate_Call {
	var _ca []interface{} = append([]interface{}{ctx}, opts...)
	return &MockGroupResolver_Invalidate_Call{Call: _e.mock.On("Invalidate", _ca...)}
}

func (_c *MockGroupResolver_Invalidate_Call) Run(run func(ctx context.Context, opts []portResolver.InvalidateOpt)) *MockGroupResolver_Invalidate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		optsArg := make([]portResolver.InvalidateOpt, 0, len(args)-1)
		for i := 1; i < len(args); i++ {
			optsArg = append(optsArg, args[i].(portResolver.InvalidateOpt))
		}
		run(args[0].(context.Context), optsArg)
	})
	return _c
}

func (_c *MockGroupResolver_Invalidate_Call) Return(_a0 error) *MockGroupResolver_Invalidate_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockGroupResolver_Invalidate_Call) RunAndReturn(run func(context.Context, []portResolver.InvalidateOpt) error) *MockGroupResolver_Invalidate_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockGroupResolver creates a new instance of MockGroupResolver. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockGroupResolver(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockGroupResolver {
	mock := &MockGroupResolver{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
