// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	resolver "github.com/adityakw90/service-access/internal/core/port/resolver"
	mock "github.com/stretchr/testify/mock"
)

// MockResolverProvider is an autogenerated mock type for the ResolverProvider type
type MockResolverProvider struct {
	mock.Mock
}

type MockResolverProvider_Expecter struct {
	mock *mock.Mock
}

func (_m *MockResolverProvider) EXPECT() *MockResolverProvider_Expecter {
	return &MockResolverProvider_Expecter{mock: &_m.Mock}
}

// Group provides a mock function with no fields
func (_m *MockResolverProvider) Group() resolver.GroupResolver {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Group")
	}

	var r0 resolver.GroupResolver
	if rf, ok := ret.Get(0).(func() resolver.GroupResolver); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(resolver.GroupResolver)
		}
	}

	return r0
}

// MockResolverProvider_Group_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Group'
type MockResolverProvider_Group_Call struct {
	*mock.Call
}

// Group is a helper method to define mock.On call
func (_e *MockResolverProvider_Expecter) Group() *MockResolverProvider_Group_Call {
	return &MockResolverProvider_Group_Call{Call: _e.mock.On("Group")}
}

func (_c *MockResolverProvider_Group_Call) Run(run func()) *MockResolverProvider_Group_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockResolverProvider_Group_Call) Return(_a0 resolver.GroupResolver) *MockResolverProvider_Group_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockResolverProvider_Group_Call) RunAndReturn(run func() resolver.GroupResolver) *MockResolverProvider_Group_Call {
	_c.Call.Return(run)
	return _c
}

// GroupPermission provides a mock function with no fields
func (_m *MockResolverProvider) GroupPermission() resolver.GroupPermissionResolver {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GroupPermission")
	}

	var r0 resolver.GroupPermissionResolver
	if rf, ok := ret.Get(0).(func() resolver.GroupPermissionResolver); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(resolver.GroupPermissionResolver)
		}
	}

	return r0
}

// MockResolverProvider_GroupPermission_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GroupPermission'
type MockResolverProvider_GroupPermission_Call struct {
	*mock.Call
}

// GroupPermission is a helper method to define mock.On call
func (_e *MockResolverProvider_Expecter) GroupPermission() *MockResolverProvider_GroupPermission_Call {
	return &MockResolverProvider_GroupPermission_Call{Call: _e.mock.On("GroupPermission")}
}

func (_c *MockResolverProvider_GroupPermission_Call) Run(run func()) *MockResolverProvider_GroupPermission_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockResolverProvider_GroupPermission_Call) Return(_a0 resolver.GroupPermissionResolver) *MockResolverProvider_GroupPermission_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockResolverProvider_GroupPermission_Call) RunAndReturn(run func() resolver.GroupPermissionResolver) *MockResolverProvider_GroupPermission_Call {
	_c.Call.Return(run)
	return _c
}

// Permission provides a mock function with no fields
func (_m *MockResolverProvider) Permission() resolver.PermissionResolver {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Permission")
	}

	var r0 resolver.PermissionResolver
	if rf, ok := ret.Get(0).(func() resolver.PermissionResolver); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(resolver.PermissionResolver)
		}
	}

	return r0
}

// MockResolverProvider_Permission_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Permission'
type MockResolverProvider_Permission_Call struct {
	*mock.Call
}

// Permission is a helper method to define mock.On call
func (_e *MockResolverProvider_Expecter) Permission() *MockResolverProvider_Permission_Call {
	return &MockResolverProvider_Permission_Call{Call: _e.mock.On("Permission")}
}

func (_c *MockResolverProvider_Permission_Call) Run(run func()) *MockResolverProvider_Permission_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockResolverProvider_Permission_Call) Return(_a0 resolver.PermissionResolver) *MockResolverProvider_Permission_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockResolverProvider_Permission_Call) RunAndReturn(run func() resolver.PermissionResolver) *MockResolverProvider_Permission_Call {
	_c.Call.Return(run)
	return _c
}

// Role provides a mock function with no fields
func (_m *MockResolverProvider) Role() resolver.RoleResolver {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Role")
	}

	var r0 resolver.RoleResolver
	if rf, ok := ret.Get(0).(func() resolver.RoleResolver); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(resolver.RoleResolver)
		}
	}

	return r0
}

// MockResolverProvider_Role_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Role'
type MockResolverProvider_Role_Call struct {
	*mock.Call
}

// Role is a helper method to define mock.On call
func (_e *MockResolverProvider_Expecter) Role() *MockResolverProvider_Role_Call {
	return &MockResolverProvider_Role_Call{Call: _e.mock.On("Role")}
}

func (_c *MockResolverProvider_Role_Call) Run(run func()) *MockResolverProvider_Role_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockResolverProvider_Role_Call) Return(_a0 resolver.RoleResolver) *MockResolverProvider_Role_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockResolverProvider_Role_Call) RunAndReturn(run func() resolver.RoleResolver) *MockResolverProvider_Role_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockResolverProvider creates a new instance of MockResolverProvider. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockResolverProvider(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockResolverProvider {
	mock := &MockResolverProvider{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
