// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	param "github.com/adityakw90/service-access/internal/core/domain/param"
	mock "github.com/stretchr/testify/mock"
)

// MockPermissionResolver is an autogenerated mock type for the PermissionResolver type
type MockPermissionResolver struct {
	mock.Mock
}

type MockPermissionResolver_Expecter struct {
	mock *mock.Mock
}

func (_m *MockPermissionResolver) EXPECT() *MockPermissionResolver_Expecter {
	return &MockPermissionResolver_Expecter{mock: &_m.Mock}
}

// IDsByResourceActions provides a mock function with given fields: ctx, resourceActions
func (_m *MockPermissionResolver) IDsByResourceActions(ctx context.Context, resourceActions []param.PermissionMapResourceAction) (map[param.PermissionMapResourceAction]int64, error) {
	ret := _m.Called(ctx, resourceActions)

	if len(ret) == 0 {
		panic("no return value specified for IDsByResourceActions")
	}

	var r0 map[param.PermissionMapResourceAction]int64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, []param.PermissionMapResourceAction) (map[param.PermissionMapResourceAction]int64, error)); ok {
		return rf(ctx, resourceActions)
	}
	if rf, ok := ret.Get(0).(func(context.Context, []param.PermissionMapResourceAction) map[param.PermissionMapResourceAction]int64); ok {
		r0 = rf(ctx, resourceActions)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[param.PermissionMapResourceAction]int64)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, []param.PermissionMapResourceAction) error); ok {
		r1 = rf(ctx, resourceActions)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockPermissionResolver_IDsByResourceActions_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IDsByResourceActions'
type MockPermissionResolver_IDsByResourceActions_Call struct {
	*mock.Call
}

// IDsByResourceActions is a helper method to define mock.On call
//   - ctx context.Context
//   - resourceActions []param.PermissionMapResourceAction
func (_e *MockPermissionResolver_Expecter) IDsByResourceActions(ctx interface{}, resourceActions interface{}) *MockPermissionResolver_IDsByResourceActions_Call {
	return &MockPermissionResolver_IDsByResourceActions_Call{Call: _e.mock.On("IDsByResourceActions", ctx, resourceActions)}
}

func (_c *MockPermissionResolver_IDsByResourceActions_Call) Run(run func(ctx context.Context, resourceActions []param.PermissionMapResourceAction)) *MockPermissionResolver_IDsByResourceActions_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].([]param.PermissionMapResourceAction))
	})
	return _c
}

func (_c *MockPermissionResolver_IDsByResourceActions_Call) Return(_a0 map[param.PermissionMapResourceAction]int64, _a1 error) *MockPermissionResolver_IDsByResourceActions_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockPermissionResolver_IDsByResourceActions_Call) RunAndReturn(run func(context.Context, []param.PermissionMapResourceAction) (map[param.PermissionMapResourceAction]int64, error)) *MockPermissionResolver_IDsByResourceActions_Call {
	_c.Call.Return(run)
	return _c
}

// IDsByUIDs provides a mock function with given fields: ctx, uids
func (_m *MockPermissionResolver) IDsByUIDs(ctx context.Context, uids []string) (map[string]int64, error) {
	ret := _m.Called(ctx, uids)

	if len(ret) == 0 {
		panic("no return value specified for IDsByUIDs")
	}

	var r0 map[string]int64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, []string) (map[string]int64, error)); ok {
		return rf(ctx, uids)
	}
	if rf, ok := ret.Get(0).(func(context.Context, []string) map[string]int64); ok {
		r0 = rf(ctx, uids)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]int64)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, []string) error); ok {
		r1 = rf(ctx, uids)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockPermissionResolver_IDsByUIDs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IDsByUIDs'
type MockPermissionResolver_IDsByUIDs_Call struct {
	*mock.Call
}

// IDsByUIDs is a helper method to define mock.On call
//   - ctx context.Context
//   - uids []string
func (_e *MockPermissionResolver_Expecter) IDsByUIDs(ctx interface{}, uids interface{}) *MockPermissionResolver_IDsByUIDs_Call {
	return &MockPermissionResolver_IDsByUIDs_Call{Call: _e.mock.On("IDsByUIDs", ctx, uids)}
}

func (_c *MockPermissionResolver_IDsByUIDs_Call) Run(run func(ctx context.Context, uids []string)) *MockPermissionResolver_IDsByUIDs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].([]string))
	})
	return _c
}

func (_c *MockPermissionResolver_IDsByUIDs_Call) Return(_a0 map[string]int64, _a1 error) *MockPermissionResolver_IDsByUIDs_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockPermissionResolver_IDsByUIDs_Call) RunAndReturn(run func(context.Context, []string) (map[string]int64, error)) *MockPermissionResolver_IDsByUIDs_Call {
	_c.Call.Return(run)
	return _c
}

// Invalidate provides a mock function with given fields: ctx, opts
func (_m *MockPermissionResolver) Invalidate(ctx context.Context, opts ...param.InvalidateOpt) error {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for Invalidate")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, ...param.InvalidateOpt) error); ok {
		r0 = rf(ctx, opts...)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockPermissionResolver_Invalidate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Invalidate'
type MockPermissionResolver_Invalidate_Call struct {
	*mock.Call
}

// Invalidate is a helper method to define mock.On call
//   - ctx context.Context
//   - opts ...param.InvalidateOpt
func (_e *MockPermissionResolver_Expecter) Invalidate(ctx interface{}, opts ...interface{}) *MockPermissionResolver_Invalidate_Call {
	return &MockPermissionResolver_Invalidate_Call{Call: _e.mock.On("Invalidate",
		append([]interface{}{ctx}, opts...)...)}
}

func (_c *MockPermissionResolver_Invalidate_Call) Run(run func(ctx context.Context, opts ...param.InvalidateOpt)) *MockPermissionResolver_Invalidate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]param.InvalidateOpt, len(args)-1)
		for i, a := range args[1:] {
			if a != nil {
				variadicArgs[i] = a.(param.InvalidateOpt)
			}
		}
		run(args[0].(context.Context), variadicArgs...)
	})
	return _c
}

func (_c *MockPermissionResolver_Invalidate_Call) Return(_a0 error) *MockPermissionResolver_Invalidate_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockPermissionResolver_Invalidate_Call) RunAndReturn(run func(context.Context, ...param.InvalidateOpt) error) *MockPermissionResolver_Invalidate_Call {
	_c.Call.Return(run)
	return _c
}

// ResourceActionsByIDs provides a mock function with given fields: ctx, ids
func (_m *MockPermissionResolver) ResourceActionsByIDs(ctx context.Context, ids []int64) (map[int64]param.PermissionMapResourceAction, error) {
	ret := _m.Called(ctx, ids)

	if len(ret) == 0 {
		panic("no return value specified for ResourceActionsByIDs")
	}

	var r0 map[int64]param.PermissionMapResourceAction
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, []int64) (map[int64]param.PermissionMapResourceAction, error)); ok {
		return rf(ctx, ids)
	}
	if rf, ok := ret.Get(0).(func(context.Context, []int64) map[int64]param.PermissionMapResourceAction); ok {
		r0 = rf(ctx, ids)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[int64]param.PermissionMapResourceAction)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, []int64) error); ok {
		r1 = rf(ctx, ids)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockPermissionResolver_ResourceActionsByIDs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ResourceActionsByIDs'
type MockPermissionResolver_ResourceActionsByIDs_Call struct {
	*mock.Call
}

// ResourceActionsByIDs is a helper method to define mock.On call
//   - ctx context.Context
//   - ids []int64
func (_e *MockPermissionResolver_Expecter) ResourceActionsByIDs(ctx interface{}, ids interface{}) *MockPermissionResolver_ResourceActionsByIDs_Call {
	return &MockPermissionResolver_ResourceActionsByIDs_Call{Call: _e.mock.On("ResourceActionsByIDs", ctx, ids)}
}

func (_c *MockPermissionResolver_ResourceActionsByIDs_Call) Run(run func(ctx context.Context, ids []int64)) *MockPermissionResolver_ResourceActionsByIDs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].([]int64))
	})
	return _c
}

func (_c *MockPermissionResolver_ResourceActionsByIDs_Call) Return(_a0 map[int64]param.PermissionMapResourceAction, _a1 error) *MockPermissionResolver_ResourceActionsByIDs_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockPermissionResolver_ResourceActionsByIDs_Call) RunAndReturn(run func(context.Context, []int64) (map[int64]param.PermissionMapResourceAction, error)) *MockPermissionResolver_ResourceActionsByIDs_Call {
	_c.Call.Return(run)
	return _c
}

// UIDsByIDs provides a mock function with given fields: ctx, ids
func (_m *MockPermissionResolver) UIDsByIDs(ctx context.Context, ids []int64) (map[int64]string, error) {
	ret := _m.Called(ctx, ids)

	if len(ret) == 0 {
		panic("no return value specified for UIDsByIDs")
	}

	var r0 map[int64]string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, []int64) (map[int64]string, error)); ok {
		return rf(ctx, ids)
	}
	if rf, ok := ret.Get(0).(func(context.Context, []int64) map[int64]string); ok {
		r0 = rf(ctx, ids)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[int64]string)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, []int64) error); ok {
		r1 = rf(ctx, ids)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockPermissionResolver_UIDsByIDs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UIDsByIDs'
type MockPermissionResolver_UIDsByIDs_Call struct {
	*mock.Call
}

// UIDsByIDs is a helper method to define mock.On call
//   - ctx context.Context
//   - ids []int64
func (_e *MockPermissionResolver_Expecter) UIDsByIDs(ctx interface{}, ids interface{}) *MockPermissionResolver_UIDsByIDs_Call {
	return &MockPermissionResolver_UIDsByIDs_Call{Call: _e.mock.On("UIDsByIDs", ctx, ids)}
}

func (_c *MockPermissionResolver_UIDsByIDs_Call) Run(run func(ctx context.Context, ids []int64)) *MockPermissionResolver_UIDsByIDs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].([]int64))
	})
	return _c
}

func (_c *MockPermissionResolver_UIDsByIDs_Call) Return(_a0 map[int64]string, _a1 error) *MockPermissionResolver_UIDsByIDs_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockPermissionResolver_UIDsByIDs_Call) RunAndReturn(run func(context.Context, []int64) (map[int64]string, error)) *MockPermissionResolver_UIDsByIDs_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockPermissionResolver creates a new instance of MockPermissionResolver. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockPermissionResolver(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockPermissionResolver {
	mock := &MockPermissionResolver{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
