// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	repository "github.com/adityakw90/service-access/internal/core/port/repository"
	mock "github.com/stretchr/testify/mock"
)

// MockRepositoryProvider is an autogenerated mock type for the RepositoryProvider type
type MockRepositoryProvider struct {
	mock.Mock
}

type MockRepositoryProvider_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRepositoryProvider) EXPECT() *MockRepositoryProvider_Expecter {
	return &MockRepositoryProvider_Expecter{mock: &_m.Mock}
}

// Group provides a mock function with no fields
func (_m *MockRepositoryProvider) Group() repository.GroupRepository {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Group")
	}

	var r0 repository.GroupRepository
	if rf, ok := ret.Get(0).(func() repository.GroupRepository); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(repository.GroupRepository)
		}
	}

	return r0
}

// MockRepositoryProvider_Group_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Group'
type MockRepositoryProvider_Group_Call struct {
	*mock.Call
}

// Group is a helper method to define mock.On call
func (_e *MockRepositoryProvider_Expecter) Group() *MockRepositoryProvider_Group_Call {
	return &MockRepositoryProvider_Group_Call{Call: _e.mock.On("Group")}
}

func (_c *MockRepositoryProvider_Group_Call) Run(run func()) *MockRepositoryProvider_Group_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockRepositoryProvider_Group_Call) Return(_a0 repository.GroupRepository) *MockRepositoryProvider_Group_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockRepositoryProvider_Group_Call) RunAndReturn(run func() repository.GroupRepository) *MockRepositoryProvider_Group_Call {
	_c.Call.Return(run)
	return _c
}

// Permission provides a mock function with no fields
func (_m *MockRepositoryProvider) Permission() repository.PermissionRepository {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Permission")
	}

	var r0 repository.PermissionRepository
	if rf, ok := ret.Get(0).(func() repository.PermissionRepository); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(repository.PermissionRepository)
		}
	}

	return r0
}

// MockRepositoryProvider_Permission_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Permission'
type MockRepositoryProvider_Permission_Call struct {
	*mock.Call
}

// Permission is a helper method to define mock.On call
func (_e *MockRepositoryProvider_Expecter) Permission() *MockRepositoryProvider_Permission_Call {
	return &MockRepositoryProvider_Permission_Call{Call: _e.mock.On("Permission")}
}

func (_c *MockRepositoryProvider_Permission_Call) Run(run func()) *MockRepositoryProvider_Permission_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockRepositoryProvider_Permission_Call) Return(_a0 repository.PermissionRepository) *MockRepositoryProvider_Permission_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockRepositoryProvider_Permission_Call) RunAndReturn(run func() repository.PermissionRepository) *MockRepositoryProvider_Permission_Call {
	_c.Call.Return(run)
	return _c
}

// Role provides a mock function with no fields
func (_m *MockRepositoryProvider) Role() repository.RoleRepository {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Role")
	}

	var r0 repository.RoleRepository
	if rf, ok := ret.Get(0).(func() repository.RoleRepository); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(repository.RoleRepository)
		}
	}

	return r0
}

// MockRepositoryProvider_Role_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Role'
type MockRepositoryProvider_Role_Call struct {
	*mock.Call
}

// Role is a helper method to define mock.On call
func (_e *MockRepositoryProvider_Expecter) Role() *MockRepositoryProvider_Role_Call {
	return &MockRepositoryProvider_Role_Call{Call: _e.mock.On("Role")}
}

func (_c *MockRepositoryProvider_Role_Call) Run(run func()) *MockRepositoryProvider_Role_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockRepositoryProvider_Role_Call) Return(_a0 repository.RoleRepository) *MockRepositoryProvider_Role_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockRepositoryProvider_Role_Call) RunAndReturn(run func() repository.RoleRepository) *MockRepositoryProvider_Role_Call {
	_c.Call.Return(run)
	return _c
}

// Subject provides a mock function with no fields
func (_m *MockRepositoryProvider) Subject() repository.SubjectRepository {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Subject")
	}

	var r0 repository.SubjectRepository
	if rf, ok := ret.Get(0).(func() repository.SubjectRepository); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(repository.SubjectRepository)
		}
	}

	return r0
}

// MockRepositoryProvider_Subject_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Subject'
type MockRepositoryProvider_Subject_Call struct {
	*mock.Call
}

// Subject is a helper method to define mock.On call
func (_e *MockRepositoryProvider_Expecter) Subject() *MockRepositoryProvider_Subject_Call {
	return &MockRepositoryProvider_Subject_Call{Call: _e.mock.On("Subject")}
}

func (_c *MockRepositoryProvider_Subject_Call) Run(run func()) *MockRepositoryProvider_Subject_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockRepositoryProvider_Subject_Call) Return(_a0 repository.SubjectRepository) *MockRepositoryProvider_Subject_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockRepositoryProvider_Subject_Call) RunAndReturn(run func() repository.SubjectRepository) *MockRepositoryProvider_Subject_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockRepositoryProvider creates a new instance of MockRepositoryProvider. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRepositoryProvider(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRepositoryProvider {
	mock := &MockRepositoryProvider{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
