// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	model "github.com/adityakw90/service-access/internal/core/domain/model"
	mock "github.com/stretchr/testify/mock"

	param "github.com/adityakw90/service-access/internal/core/domain/param"
)

// MockGroupRepository is an autogenerated mock type for the GroupRepository type
type MockGroupRepository struct {
	mock.Mock
}

type MockGroupRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockGroupRepository) EXPECT() *MockGroupRepository_Expecter {
	return &MockGroupRepository_Expecter{mock: &_m.Mock}
}

// AddPermission provides a mock function with given fields: ctx, groupID, permissionID, uid
func (_m *MockGroupRepository) AddPermission(ctx context.Context, groupID int64, permissionID int64, uid string) error {
	ret := _m.Called(ctx, groupID, permissionID, uid)

	if len(ret) == 0 {
		panic("no return value specified for AddPermission")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int64, int64, string) error); ok {
		r0 = rf(ctx, groupID, permissionID, uid)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockGroupRepository_AddPermission_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddPermission'
type MockGroupRepository_AddPermission_Call struct {
	*mock.Call
}

// AddPermission is a helper method to define mock.On call
//   - ctx context.Context
//   - groupID int64
//   - permissionID int64
//   - uid string
func (_e *MockGroupRepository_Expecter) AddPermission(ctx interface{}, groupID interface{}, permissionID interface{}, uid interface{}) *MockGroupRepository_AddPermission_Call {
	return &MockGroupRepository_AddPermission_Call{Call: _e.mock.On("AddPermission", ctx, groupID, permissionID, uid)}
}

func (_c *MockGroupRepository_AddPermission_Call) Run(run func(ctx context.Context, groupID int64, permissionID int64, uid string)) *MockGroupRepository_AddPermission_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64), args[2].(int64), args[3].(string))
	})
	return _c
}

func (_c *MockGroupRepository_AddPermission_Call) Return(_a0 error) *MockGroupRepository_AddPermission_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockGroupRepository_AddPermission_Call) RunAndReturn(run func(context.Context, int64, int64, string) error) *MockGroupRepository_AddPermission_Call {
	_c.Call.Return(run)
	return _c
}

// Create provides a mock function with given fields: ctx, group
func (_m *MockGroupRepository) Create(ctx context.Context, group *model.Group) error {
	ret := _m.Called(ctx, group)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *model.Group) error); ok {
		r0 = rf(ctx, group)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockGroupRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockGroupRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - group *model.Group
func (_e *MockGroupRepository_Expecter) Create(ctx interface{}, group interface{}) *MockGroupRepository_Create_Call {
	return &MockGroupRepository_Create_Call{Call: _e.mock.On("Create", ctx, group)}
}

func (_c *MockGroupRepository_Create_Call) Run(run func(ctx context.Context, group *model.Group)) *MockGroupRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*model.Group))
	})
	return _c
}

func (_c *MockGroupRepository_Create_Call) Return(_a0 error) *MockGroupRepository_Create_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockGroupRepository_Create_Call) RunAndReturn(run func(context.Context, *model.Group) error) *MockGroupRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function with given fields: ctx, id
func (_m *MockGroupRepository) Delete(ctx context.Context, id int64) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockGroupRepository_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockGroupRepository_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - id int64
func (_e *MockGroupRepository_Expecter) Delete(ctx interface{}, id interface{}) *MockGroupRepository_Delete_Call {
	return &MockGroupRepository_Delete_Call{Call: _e.mock.On("Delete", ctx, id)}
}

func (_c *MockGroupRepository_Delete_Call) Run(run func(ctx context.Context, id int64)) *MockGroupRepository_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64))
	})
	return _c
}

func (_c *MockGroupRepository_Delete_Call) Return(_a0 error) *MockGroupRepository_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockGroupRepository_Delete_Call) RunAndReturn(run func(context.Context, int64) error) *MockGroupRepository_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// GetByID provides a mock function with given fields: ctx, id
func (_m *MockGroupRepository) GetByID(ctx context.Context, id int64) (*model.Group, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *model.Group
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) (*model.Group, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64) *model.Group); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Group)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockGroupRepository_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type MockGroupRepository_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id int64
func (_e *MockGroupRepository_Expecter) GetByID(ctx interface{}, id interface{}) *MockGroupRepository_GetByID_Call {
	return &MockGroupRepository_GetByID_Call{Call: _e.mock.On("GetByID", ctx, id)}
}

func (_c *MockGroupRepository_GetByID_Call) Run(run func(ctx context.Context, id int64)) *MockGroupRepository_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64))
	})
	return _c
}

func (_c *MockGroupRepository_GetByID_Call) Return(_a0 *model.Group, _a1 error) *MockGroupRepository_GetByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockGroupRepository_GetByID_Call) RunAndReturn(run func(context.Context, int64) (*model.Group, error)) *MockGroupRepository_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// GetByUID provides a mock function with given fields: ctx, uid
func (_m *MockGroupRepository) GetByUID(ctx context.Context, uid string) (*model.Group, error) {
	ret := _m.Called(ctx, uid)

	if len(ret) == 0 {
		panic("no return value specified for GetByUID")
	}

	var r0 *model.Group
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*model.Group, error)); ok {
		return rf(ctx, uid)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *model.Group); ok {
		r0 = rf(ctx, uid)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Group)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, uid)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockGroupRepository_GetByUID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByUID'
type MockGroupRepository_GetByUID_Call struct {
	*mock.Call
}

// GetByUID is a helper method to define mock.On call
//   - ctx context.Context
//   - uid string
func (_e *MockGroupRepository_Expecter) GetByUID(ctx interface{}, uid interface{}) *MockGroupRepository_GetByUID_Call {
	return &MockGroupRepository_GetByUID_Call{Call: _e.mock.On("GetByUID", ctx, uid)}
}

func (_c *MockGroupRepository_GetByUID_Call) Run(run func(ctx context.Context, uid string)) *MockGroupRepository_GetByUID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockGroupRepository_GetByUID_Call) Return(_a0 *model.Group, _a1 error) *MockGroupRepository_GetByUID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockGroupRepository_GetByUID_Call) RunAndReturn(run func(context.Context, string) (*model.Group, error)) *MockGroupRepository_GetByUID_Call {
	_c.Call.Return(run)
	return _c
}

// GetPermissionByGroupIDAndPermissionUID provides a mock function with given fields: ctx, groupID, permissionUID
func (_m *MockGroupRepository) GetPermissionByGroupIDAndPermissionUID(ctx context.Context, groupID int64, permissionUID string) (*model.GroupPermission, error) {
	ret := _m.Called(ctx, groupID, permissionUID)

	if len(ret) == 0 {
		panic("no return value specified for GetPermissionByGroupIDAndPermissionUID")
	}

	var r0 *model.GroupPermission
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64, string) (*model.GroupPermission, error)); ok {
		return rf(ctx, groupID, permissionUID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64, string) *model.GroupPermission); ok {
		r0 = rf(ctx, groupID, permissionUID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.GroupPermission)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64, string) error); ok {
		r1 = rf(ctx, groupID, permissionUID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockGroupRepository_GetPermissionByGroupIDAndPermissionUID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetPermissionByGroupIDAndPermissionUID'
type MockGroupRepository_GetPermissionByGroupIDAndPermissionUID_Call struct {
	*mock.Call
}

// GetPermissionByGroupIDAndPermissionUID is a helper method to define mock.On call
//   - ctx context.Context
//   - groupID int64
//   - permissionUID string
func (_e *MockGroupRepository_Expecter) GetPermissionByGroupIDAndPermissionUID(ctx interface{}, groupID interface{}, permissionUID interface{}) *MockGroupRepository_GetPermissionByGroupIDAndPermissionUID_Call {
	return &MockGroupRepository_GetPermissionByGroupIDAndPermissionUID_Call{Call: _e.mock.On("GetPermissionByGroupIDAndPermissionUID", ctx, groupID, permissionUID)}
}

func (_c *MockGroupRepository_GetPermissionByGroupIDAndPermissionUID_Call) Run(run func(ctx context.Context, groupID int64, permissionUID string)) *MockGroupRepository_GetPermissionByGroupIDAndPermissionUID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64), args[2].(string))
	})
	return _c
}

func (_c *MockGroupRepository_GetPermissionByGroupIDAndPermissionUID_Call) Return(_a0 *model.GroupPermission, _a1 error) *MockGroupRepository_GetPermissionByGroupIDAndPermissionUID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockGroupRepository_GetPermissionByGroupIDAndPermissionUID_Call) RunAndReturn(run func(context.Context, int64, string) (*model.GroupPermission, error)) *MockGroupRepository_GetPermissionByGroupIDAndPermissionUID_Call {
	_c.Call.Return(run)
	return _c
}

// GetPermissionByID provides a mock function with given fields: ctx, groupPermissionID
func (_m *MockGroupRepository) GetPermissionByID(ctx context.Context, groupPermissionID int64) (*model.GroupPermission, error) {
	ret := _m.Called(ctx, groupPermissionID)

	if len(ret) == 0 {
		panic("no return value specified for GetPermissionByID")
	}

	var r0 *model.GroupPermission
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) (*model.GroupPermission, error)); ok {
		return rf(ctx, groupPermissionID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64) *model.GroupPermission); ok {
		r0 = rf(ctx, groupPermissionID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.GroupPermission)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = rf(ctx, groupPermissionID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockGroupRepository_GetPermissionByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetPermissionByID'
type MockGroupRepository_GetPermissionByID_Call struct {
	*mock.Call
}

// GetPermissionByID is a helper method to define mock.On call
//   - ctx context.Context
//   - groupPermissionID int64
func (_e *MockGroupRepository_Expecter) GetPermissionByID(ctx interface{}, groupPermissionID interface{}) *MockGroupRepository_GetPermissionByID_Call {
	return &MockGroupRepository_GetPermissionByID_Call{Call: _e.mock.On("GetPermissionByID", ctx, groupPermissionID)}
}

func (_c *MockGroupRepository_GetPermissionByID_Call) Run(run func(ctx context.Context, groupPermissionID int64)) *MockGroupRepository_GetPermissionByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64))
	})
	return _c
}

func (_c *MockGroupRepository_GetPermissionByID_Call) Return(_a0 *model.GroupPermission, _a1 error) *MockGroupRepository_GetPermissionByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockGroupRepository_GetPermissionByID_Call) RunAndReturn(run func(context.Context, int64) (*model.GroupPermission, error)) *MockGroupRepository_GetPermissionByID_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function with given fields: ctx, pagination, filter
func (_m *MockGroupRepository) List(ctx context.Context, pagination *param.PaginationParam, filter *param.GroupListFilterParam) (model.Groups, error) {
	ret := _m.Called(ctx, pagination, filter)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 model.Groups
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *param.PaginationParam, *param.GroupListFilterParam) (model.Groups, error)); ok {
		return rf(ctx, pagination, filter)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *param.PaginationParam, *param.GroupListFilterParam) model.Groups); ok {
		r0 = rf(ctx, pagination, filter)
	} else {
		r0 = ret.Get(0).(model.Groups)
	}

	if rf, ok := ret.Get(1).(func(context.Context, *param.PaginationParam, *param.GroupListFilterParam) error); ok {
		r1 = rf(ctx, pagination, filter)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockGroupRepository_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type MockGroupRepository_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
//   - pagination *param.PaginationParam
//   - filter *param.GroupListFilterParam
func (_e *MockGroupRepository_Expecter) List(ctx interface{}, pagination interface{}, filter interface{}) *MockGroupRepository_List_Call {
	return &MockGroupRepository_List_Call{Call: _e.mock.On("List", ctx, pagination, filter)}
}

func (_c *MockGroupRepository_List_Call) Run(run func(ctx context.Context, pagination *param.PaginationParam, filter *param.GroupListFilterParam)) *MockGroupRepository_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*param.PaginationParam), args[2].(*param.GroupListFilterParam))
	})
	return _c
}

func (_c *MockGroupRepository_List_Call) Return(_a0 model.Groups, _a1 error) *MockGroupRepository_List_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockGroupRepository_List_Call) RunAndReturn(run func(context.Context, *param.PaginationParam, *param.GroupListFilterParam) (model.Groups, error)) *MockGroupRepository_List_Call {
	_c.Call.Return(run)
	return _c
}

// ListPermission provides a mock function with given fields: ctx, groupID, pagination, filter
func (_m *MockGroupRepository) ListPermission(ctx context.Context, groupID int64, pagination *param.PaginationParam, filter *param.GroupPermissionListFilterParam) (model.GroupPermissions, error) {
	ret := _m.Called(ctx, groupID, pagination, filter)

	if len(ret) == 0 {
		panic("no return value specified for ListPermission")
	}

	var r0 model.GroupPermissions
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64, *param.PaginationParam, *param.GroupPermissionListFilterParam) (model.GroupPermissions, error)); ok {
		return rf(ctx, groupID, pagination, filter)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64, *param.PaginationParam, *param.GroupPermissionListFilterParam) model.GroupPermissions); ok {
		r0 = rf(ctx, groupID, pagination, filter)
	} else {
		r0 = ret.Get(0).(model.GroupPermissions)
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64, *param.PaginationParam, *param.GroupPermissionListFilterParam) error); ok {
		r1 = rf(ctx, groupID, pagination, filter)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockGroupRepository_ListPermission_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListPermission'
type MockGroupRepository_ListPermission_Call struct {
	*mock.Call
}

// ListPermission is a helper method to define mock.On call
//   - ctx context.Context
//   - groupID int64
//   - pagination *param.PaginationParam
//   - filter *param.GroupPermissionListFilterParam
func (_e *MockGroupRepository_Expecter) ListPermission(ctx interface{}, groupID interface{}, pagination interface{}, filter interface{}) *MockGroupRepository_ListPermission_Call {
	return &MockGroupRepository_ListPermission_Call{Call: _e.mock.On("ListPermission", ctx, groupID, pagination, filter)}
}

func (_c *MockGroupRepository_ListPermission_Call) Run(run func(ctx context.Context, groupID int64, pagination *param.PaginationParam, filter *param.GroupPermissionListFilterParam)) *MockGroupRepository_ListPermission_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64), args[2].(*param.PaginationParam), args[3].(*param.GroupPermissionListFilterParam))
	})
	return _c
}

func (_c *MockGroupRepository_ListPermission_Call) Return(_a0 model.GroupPermissions, _a1 error) *MockGroupRepository_ListPermission_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockGroupRepository_ListPermission_Call) RunAndReturn(run func(context.Context, int64, *param.PaginationParam, *param.GroupPermissionListFilterParam) (model.GroupPermissions, error)) *MockGroupRepository_ListPermission_Call {
	_c.Call.Return(run)
	return _c
}

// RemovePermission provides a mock function with given fields: ctx, groupID, permissionID
func (_m *MockGroupRepository) RemovePermission(ctx context.Context, groupID int64, permissionID int64) error {
	ret := _m.Called(ctx, groupID, permissionID)

	if len(ret) == 0 {
		panic("no return value specified for RemovePermission")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int64, int64) error); ok {
		r0 = rf(ctx, groupID, permissionID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockGroupRepository_RemovePermission_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RemovePermission'
type MockGroupRepository_RemovePermission_Call struct {
	*mock.Call
}

// RemovePermission is a helper method to define mock.On call
//   - ctx context.Context
//   - groupID int64
//   - permissionID int64
func (_e *MockGroupRepository_Expecter) RemovePermission(ctx interface{}, groupID interface{}, permissionID interface{}) *MockGroupRepository_RemovePermission_Call {
	return &MockGroupRepository_RemovePermission_Call{Call: _e.mock.On("RemovePermission", ctx, groupID, permissionID)}
}

func (_c *MockGroupRepository_RemovePermission_Call) Run(run func(ctx context.Context, groupID int64, permissionID int64)) *MockGroupRepository_RemovePermission_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64), args[2].(int64))
	})
	return _c
}

func (_c *MockGroupRepository_RemovePermission_Call) Return(_a0 error) *MockGroupRepository_RemovePermission_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockGroupRepository_RemovePermission_Call) RunAndReturn(run func(context.Context, int64, int64) error) *MockGroupRepository_RemovePermission_Call {
	_c.Call.Return(run)
	return _c
}

// ReplacePermission provides a mock function with given fields: ctx, groupID, permissionIDs, uids
func (_m *MockGroupRepository) ReplacePermission(ctx context.Context, groupID int64, permissionIDs []int64, uids []string) error {
	ret := _m.Called(ctx, groupID, permissionIDs, uids)

	if len(ret) == 0 {
		panic("no return value specified for ReplacePermission")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int64, []int64, []string) error); ok {
		r0 = rf(ctx, groupID, permissionIDs, uids)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockGroupRepository_ReplacePermission_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ReplacePermission'
type MockGroupRepository_ReplacePermission_Call struct {
	*mock.Call
}

// ReplacePermission is a helper method to define mock.On call
//   - ctx context.Context
//   - groupID int64
//   - permissionIDs []int64
//   - uids []string
func (_e *MockGroupRepository_Expecter) ReplacePermission(ctx interface{}, groupID interface{}, permissionIDs interface{}, uids interface{}) *MockGroupRepository_ReplacePermission_Call {
	return &MockGroupRepository_ReplacePermission_Call{Call: _e.mock.On("ReplacePermission", ctx, groupID, permissionIDs, uids)}
}

func (_c *MockGroupRepository_ReplacePermission_Call) Run(run func(ctx context.Context, groupID int64, permissionIDs []int64, uids []string)) *MockGroupRepository_ReplacePermission_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64), args[2].([]int64), args[3].([]string))
	})
	return _c
}

func (_c *MockGroupRepository_ReplacePermission_Call) Return(_a0 error) *MockGroupRepository_ReplacePermission_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockGroupRepository_ReplacePermission_Call) RunAndReturn(run func(context.Context, int64, []int64, []string) error) *MockGroupRepository_ReplacePermission_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: ctx, group
func (_m *MockGroupRepository) Update(ctx context.Context, group *model.Group) error {
	ret := _m.Called(ctx, group)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *model.Group) error); ok {
		r0 = rf(ctx, group)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockGroupRepository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockGroupRepository_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - group *model.Group
func (_e *MockGroupRepository_Expecter) Update(ctx interface{}, group interface{}) *MockGroupRepository_Update_Call {
	return &MockGroupRepository_Update_Call{Call: _e.mock.On("Update", ctx, group)}
}

func (_c *MockGroupRepository_Update_Call) Run(run func(ctx context.Context, group *model.Group)) *MockGroupRepository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*model.Group))
	})
	return _c
}

func (_c *MockGroupRepository_Update_Call) Return(_a0 error) *MockGroupRepository_Update_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockGroupRepository_Update_Call) RunAndReturn(run func(context.Context, *model.Group) error) *MockGroupRepository_Update_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockGroupRepository creates a new instance of MockGroupRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockGroupRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockGroupRepository {
	mock := &MockGroupRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
